// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT COUNT(*) FROM audit_logs
WHERE organization_id = $1
  AND document_type = $2
  AND document_id   = $3
`

func (q *Queries) CountAuditEvents(ctx context.Context, organizationID string, documentType string, documentID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents, organizationID, documentType, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogs = `-- name: CountAuditLogs :one

SELECT COUNT(*) FROM audit_logs
WHERE organization_id = $1
  AND ($2::text = '' OR action        = $2)
  AND ($3::text = '' OR document_type = $3)
  AND ($4::text = '' OR user_id       = $4)
`

// Audit log queries
// Uses empty-string = skip-filter pattern to avoid nullable params.
// All queries return the full row (no preloads needed for audit logs).
func (q *Queries) CountAuditLogs(ctx context.Context, organizationID string, column2 string, column3 string, column4 string) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		organizationID,
		column2,
		column3,
		column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentAuditLogs = `-- name: CountDocumentAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE organization_id = $1
  AND document_id = $2
`

func (q *Queries) CountDocumentAuditLogs(ctx context.Context, organizationID string, documentID string) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentAuditLogs, organizationID, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, organization_id, document_id, document_type,
       user_id, actor_name, actor_role, action, changes, details, created_at
FROM audit_logs
WHERE organization_id = $1
  AND document_type = $2
  AND document_id   = $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAuditEventsRow struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	DocumentID     string             `json:"document_id"`
	DocumentType   string             `json:"document_type"`
	UserID         string             `json:"user_id"`
	ActorName      string             `json:"actor_name"`
	ActorRole      string             `json:"actor_role"`
	Action         string             `json:"action"`
	Changes        []byte             `json:"changes"`
	Details        []byte             `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, organizationID string, documentType string, documentID string, limit int32, offset int32) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		organizationID,
		documentType,
		documentID,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsRow{}
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentID,
			&i.DocumentType,
			&i.UserID,
			&i.ActorName,
			&i.ActorRole,
			&i.Action,
			&i.Changes,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, organization_id, document_id, document_type,
       user_id, actor_name, actor_role, action, changes, details, created_at
FROM audit_logs
WHERE organization_id = $1
  AND ($2::text = '' OR action        = $2)
  AND ($3::text = '' OR document_type = $3)
  AND ($4::text = '' OR user_id       = $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListAuditLogsParams struct {
	OrganizationID string `json:"organization_id"`
	Column2        string `json:"column_2"`
	Column3        string `json:"column_3"`
	Column4        string `json:"column_4"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

type ListAuditLogsRow struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	DocumentID     string             `json:"document_id"`
	DocumentType   string             `json:"document_type"`
	UserID         string             `json:"user_id"`
	ActorName      string             `json:"actor_name"`
	ActorRole      string             `json:"actor_role"`
	Action         string             `json:"action"`
	Changes        []byte             `json:"changes"`
	Details        []byte             `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentID,
			&i.DocumentType,
			&i.UserID,
			&i.ActorName,
			&i.ActorRole,
			&i.Action,
			&i.Changes,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentAuditLogs = `-- name: ListDocumentAuditLogs :many
SELECT id, organization_id, document_id, document_type,
       user_id, actor_name, actor_role, action, changes, details, created_at
FROM audit_logs
WHERE organization_id = $1
  AND document_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListDocumentAuditLogsRow struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	DocumentID     string             `json:"document_id"`
	DocumentType   string             `json:"document_type"`
	UserID         string             `json:"user_id"`
	ActorName      string             `json:"actor_name"`
	ActorRole      string             `json:"actor_role"`
	Action         string             `json:"action"`
	Changes        []byte             `json:"changes"`
	Details        []byte             `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDocumentAuditLogs(ctx context.Context, organizationID string, documentID string, limit int32, offset int32) ([]ListDocumentAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentAuditLogs,
		organizationID,
		documentID,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentAuditLogsRow{}
	for rows.Next() {
		var i ListDocumentAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentID,
			&i.DocumentType,
			&i.UserID,
			&i.ActorName,
			&i.ActorRole,
			&i.Action,
			&i.Changes,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
