// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document_enrichment.sql

package db

import (
	"context"
)

const getLinkedPOsForRequisitions = `-- name: GetLinkedPOsForRequisitions :many

SELECT DISTINCT ON (source_requisition_id)
    source_requisition_id,
    id,
    document_number,
    status
FROM purchase_orders
WHERE source_requisition_id = ANY($1::text[])
  AND organization_id = $2
  AND UPPER(status) != 'CANCELLED'
ORDER BY source_requisition_id, created_at DESC
`

type GetLinkedPOsForRequisitionsRow struct {
	SourceRequisitionID *string `json:"source_requisition_id"`
	ID                  string  `json:"id"`
	DocumentNumber      string  `json:"document_number"`
	Status              *string `json:"status"`
}

// Batch enrichment queries for document cross-linking.
// These replace the existing config.DB.Raw(DISTINCT ON...) calls in the list handlers.
// pgx/v5 encodes []string natively for the ANY($n::text[]) array parameter.
func (q *Queries) GetLinkedPOsForRequisitions(ctx context.Context, column1 []string, organizationID string) ([]GetLinkedPOsForRequisitionsRow, error) {
	rows, err := q.db.Query(ctx, getLinkedPOsForRequisitions, column1, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLinkedPOsForRequisitionsRow{}
	for rows.Next() {
		var i GetLinkedPOsForRequisitionsRow
		if err := rows.Scan(
			&i.SourceRequisitionID,
			&i.ID,
			&i.DocumentNumber,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkedPVsForPurchaseOrders = `-- name: GetLinkedPVsForPurchaseOrders :many
SELECT DISTINCT ON (linked_po)
    linked_po,
    id,
    document_number,
    status
FROM payment_vouchers
WHERE linked_po = ANY($1::text[])
  AND organization_id = $2
  AND UPPER(status) != 'CANCELLED'
ORDER BY linked_po, created_at DESC
`

type GetLinkedPVsForPurchaseOrdersRow struct {
	LinkedPo       *string `json:"linked_po"`
	ID             string  `json:"id"`
	DocumentNumber string  `json:"document_number"`
	Status         *string `json:"status"`
}

func (q *Queries) GetLinkedPVsForPurchaseOrders(ctx context.Context, column1 []string, organizationID string) ([]GetLinkedPVsForPurchaseOrdersRow, error) {
	rows, err := q.db.Query(ctx, getLinkedPVsForPurchaseOrders, column1, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLinkedPVsForPurchaseOrdersRow{}
	for rows.Next() {
		var i GetLinkedPVsForPurchaseOrdersRow
		if err := rows.Scan(
			&i.LinkedPo,
			&i.ID,
			&i.DocumentNumber,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
