// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: grns.sql

package db

import (
	"context"
)

const countGRNsAll = `-- name: CountGRNsAll :one

SELECT COUNT(*) FROM goods_received_notes
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status)           = UPPER($2))
  AND ($3::text = '' OR po_document_number      = $3)
  AND (NOT $4::bool OR EXISTS (
        SELECT 1 FROM purchase_orders po
        WHERE po.document_number = po_document_number
          AND po.routing_type != 'direct_payment'
      ))
`

type CountGRNsAllParams struct {
	OrganizationID    string `json:"organization_id"`
	Column2           string `json:"column_2"`
	Column3           string `json:"column_3"`
	HideDirectPayment bool   `json:"hide_direct_payment"`
}

// Goods received note read queries.
// Both CanViewAll and IsProcurement use the unfiltered path (ApplyToQuery passes through).
// Limited adds owner (created_by OR received_by) + workflow_tasks involvement.
func (q *Queries) CountGRNsAll(ctx context.Context, arg CountGRNsAllParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGRNsAll,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.HideDirectPayment,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGRNsLimited = `-- name: CountGRNsLimited :one
SELECT COUNT(*) FROM goods_received_notes g
WHERE g.organization_id = $1
  AND ($2::text = '' OR UPPER(g.status)          = UPPER($2))
  AND ($3::text = '' OR g.po_document_number     = $3)
  AND (
      g.created_by  = $4
      OR g.received_by = $4
      OR g.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'grn'
            AND (
                wt.assigned_user_id        = $4
                OR LOWER(wt.assigned_role) = LOWER($5)
                OR wt.assigned_role        = ANY($6::text[])
                OR wt.claimed_by           = $4
            )
      )
  )
`

type CountGRNsLimitedParams struct {
	OrganizationID string   `json:"organization_id"`
	Column2        string   `json:"column_2"`
	Column3        string   `json:"column_3"`
	CreatedBy      *string  `json:"created_by"`
	Lower          string   `json:"lower"`
	Column6        []string `json:"column_6"`
}

func (q *Queries) CountGRNsLimited(ctx context.Context, arg CountGRNsLimitedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGRNsLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.CreatedBy,
		arg.Lower,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listGRNIDsAll = `-- name: ListGRNIDsAll :many
SELECT id FROM goods_received_notes
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status)           = UPPER($2))
  AND ($3::text = '' OR po_document_number      = $3)
  AND (NOT $4::bool OR EXISTS (
        SELECT 1 FROM purchase_orders po
        WHERE po.document_number = po_document_number
          AND po.routing_type != 'direct_payment'
      ))
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListGRNIDsAllParams struct {
	OrganizationID    string `json:"organization_id"`
	Column2           string `json:"column_2"`
	Column3           string `json:"column_3"`
	HideDirectPayment bool   `json:"hide_direct_payment"`
	Limit             int32  `json:"limit"`
	Offset            int32  `json:"offset"`
}

func (q *Queries) ListGRNIDsAll(ctx context.Context, arg ListGRNIDsAllParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listGRNIDsAll,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.HideDirectPayment,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGRNIDsLimited = `-- name: ListGRNIDsLimited :many
SELECT g.id FROM goods_received_notes g
WHERE g.organization_id = $1
  AND ($2::text = '' OR UPPER(g.status)          = UPPER($2))
  AND ($3::text = '' OR g.po_document_number     = $3)
  AND (
      g.created_by  = $4
      OR g.received_by = $4
      OR g.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'grn'
            AND (
                wt.assigned_user_id        = $4
                OR LOWER(wt.assigned_role) = LOWER($5)
                OR wt.assigned_role        = ANY($6::text[])
                OR wt.claimed_by           = $4
            )
      )
  )
ORDER BY g.created_at DESC
LIMIT $7 OFFSET $8
`

type ListGRNIDsLimitedParams struct {
	OrganizationID string   `json:"organization_id"`
	Column2        string   `json:"column_2"`
	Column3        string   `json:"column_3"`
	CreatedBy      *string  `json:"created_by"`
	Lower          string   `json:"lower"`
	Column6        []string `json:"column_6"`
	Limit          int32    `json:"limit"`
	Offset         int32    `json:"offset"`
}

func (q *Queries) ListGRNIDsLimited(ctx context.Context, arg ListGRNIDsLimitedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listGRNIDsLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.CreatedBy,
		arg.Lower,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
