// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoginAttempt = `-- name: CreateLoginAttempt :one
INSERT INTO login_attempts (
    user_id, email, ip_address, user_agent, success, failure_reason
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, email, ip_address, user_agent, success, failure_reason, attempted_at
`

type CreateLoginAttemptParams struct {
	UserID        *string `json:"user_id"`
	Email         string  `json:"email"`
	IpAddress     *string `json:"ip_address"`
	UserAgent     *string `json:"user_agent"`
	Success       bool    `json:"success"`
	FailureReason *string `json:"failure_reason"`
}

func (q *Queries) CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, createLoginAttempt,
		arg.UserID,
		arg.Email,
		arg.IpAddress,
		arg.UserAgent,
		arg.Success,
		arg.FailureReason,
	)
	var i LoginAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.IpAddress,
		&i.UserAgent,
		&i.Success,
		&i.FailureReason,
		&i.AttemptedAt,
	)
	return i, err
}

const deleteOldLoginAttempts = `-- name: DeleteOldLoginAttempts :exec
DELETE FROM login_attempts WHERE attempted_at < $1
`

func (q *Queries) DeleteOldLoginAttempts(ctx context.Context, attemptedAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteOldLoginAttempts, attemptedAt)
	return err
}

const getLoginAttemptsByEmail = `-- name: GetLoginAttemptsByEmail :many
SELECT id, user_id, email, ip_address, user_agent, success, failure_reason, attempted_at FROM login_attempts 
WHERE email = $1 
ORDER BY attempted_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) GetLoginAttemptsByEmail(ctx context.Context, email string, limit int32, offset int32) ([]LoginAttempt, error) {
	rows, err := q.db.Query(ctx, getLoginAttemptsByEmail, email, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginAttempt{}
	for rows.Next() {
		var i LoginAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.IpAddress,
			&i.UserAgent,
			&i.Success,
			&i.FailureReason,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoginAttemptsByUser = `-- name: GetLoginAttemptsByUser :many
SELECT id, user_id, email, ip_address, user_agent, success, failure_reason, attempted_at FROM login_attempts 
WHERE user_id = $1 
ORDER BY attempted_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) GetLoginAttemptsByUser(ctx context.Context, userID *string, limit int32, offset int32) ([]LoginAttempt, error) {
	rows, err := q.db.Query(ctx, getLoginAttemptsByUser, userID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginAttempt{}
	for rows.Next() {
		var i LoginAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.IpAddress,
			&i.UserAgent,
			&i.Success,
			&i.FailureReason,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentFailedAttempts = `-- name: GetRecentFailedAttempts :one
SELECT COUNT(*) FROM login_attempts 
WHERE email = $1 AND success = false AND attempted_at > $2
`

func (q *Queries) GetRecentFailedAttempts(ctx context.Context, email string, attemptedAt pgtype.Timestamp) (int64, error) {
	row := q.db.QueryRow(ctx, getRecentFailedAttempts, email, attemptedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRecentFailedAttemptsByIP = `-- name: GetRecentFailedAttemptsByIP :one
SELECT COUNT(*) FROM login_attempts 
WHERE ip_address = $1 AND success = false AND attempted_at > $2
`

func (q *Queries) GetRecentFailedAttemptsByIP(ctx context.Context, ipAddress *string, attemptedAt pgtype.Timestamp) (int64, error) {
	row := q.db.QueryRow(ctx, getRecentFailedAttemptsByIP, ipAddress, attemptedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}
