// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountLockout struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    string           `json:"user_id"`
	Email     string           `json:"email"`
	IpAddress *string          `json:"ip_address"`
	Reason    string           `json:"reason"`
	LockedAt  pgtype.Timestamp `json:"locked_at"`
	UnlocksAt pgtype.Timestamp `json:"unlocks_at"`
	Active    *bool            `json:"active"`
}

type ApprovalHistory struct {
	ID        pgtype.UUID      `json:"id"`
	TaskID    pgtype.UUID      `json:"task_id"`
	UserID    string           `json:"user_id"`
	Action    string           `json:"action"`
	Stage     int32            `json:"stage"`
	Comment   *string          `json:"comment"`
	Signature *string          `json:"signature"`
	IpAddress *string          `json:"ip_address"`
	UserAgent *string          `json:"user_agent"`
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type ApprovalTask struct {
	ID              string           `json:"id"`
	OrganizationID  string           `json:"organization_id"`
	DocumentID      string           `json:"document_id"`
	DocumentType    string           `json:"document_type"`
	ApproverID      string           `json:"approver_id"`
	AssignedTo      string           `json:"assigned_to"`
	Status          *string          `json:"status"`
	Stage           *int32           `json:"stage"`
	Comments        *string          `json:"comments"`
	Signature       *string          `json:"signature"`
	ApprovedBy      *string          `json:"approved_by"`
	ApprovedAt      pgtype.Timestamp `json:"approved_at"`
	RejectedBy      *string          `json:"rejected_by"`
	RejectedAt      pgtype.Timestamp `json:"rejected_at"`
	RejectionReason *string          `json:"rejection_reason"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type ApprovalTasksEnhanced struct {
	ID             pgtype.UUID      `json:"id"`
	OrganizationID string           `json:"organization_id"`
	DocumentID     string           `json:"document_id"`
	DocumentType   string           `json:"document_type"`
	WorkflowID     pgtype.UUID      `json:"workflow_id"`
	AssignedTo     string           `json:"assigned_to"`
	AssignedBy     *string          `json:"assigned_by"`
	Status         string           `json:"status"`
	CurrentStage   int32            `json:"current_stage"`
	TotalStages    int32            `json:"total_stages"`
	Priority       *string          `json:"priority"`
	DueDate        pgtype.Timestamp `json:"due_date"`
	Notes          *string          `json:"notes"`
	Metadata       []byte           `json:"metadata"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type AuditLog struct {
	ID           string           `json:"id"`
	DocumentID   string           `json:"document_id"`
	DocumentType string           `json:"document_type"`
	UserID       string           `json:"user_id"`
	Action       string           `json:"action"`
	Changes      []byte           `json:"changes"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Budget struct {
	ID              string           `json:"id"`
	OrganizationID  string           `json:"organization_id"`
	OwnerID         string           `json:"owner_id"`
	BudgetCode      string           `json:"budget_code"`
	Department      *string          `json:"department"`
	Status          *string          `json:"status"`
	FiscalYear      *string          `json:"fiscal_year"`
	TotalBudget     pgtype.Numeric   `json:"total_budget"`
	AllocatedAmount pgtype.Numeric   `json:"allocated_amount"`
	RemainingAmount pgtype.Numeric   `json:"remaining_amount"`
	ApprovalStage   *int32           `json:"approval_stage"`
	ApprovalHistory []byte           `json:"approval_history"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type Category struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Name           string           `json:"name"`
	Description    *string          `json:"description"`
	Active         *bool            `json:"active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type CategoryBudgetCode struct {
	ID         string           `json:"id"`
	CategoryID string           `json:"category_id"`
	BudgetCode string           `json:"budget_code"`
	Active     *bool            `json:"active"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type EmailVerification struct {
	ID         pgtype.UUID      `json:"id"`
	UserID     string           `json:"user_id"`
	Email      string           `json:"email"`
	Token      string           `json:"token"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	VerifiedAt pgtype.Timestamp `json:"verified_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type GoodsReceivedNote struct {
	ID              string           `json:"id"`
	OrganizationID  string           `json:"organization_id"`
	GrnNumber       string           `json:"grn_number"`
	PoNumber        *string          `json:"po_number"`
	Status          *string          `json:"status"`
	ReceivedDate    pgtype.Timestamp `json:"received_date"`
	ReceivedBy      *string          `json:"received_by"`
	Items           []byte           `json:"items"`
	QualityIssues   []byte           `json:"quality_issues"`
	ApprovalStage   *int32           `json:"approval_stage"`
	ApprovalHistory []byte           `json:"approval_history"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type LoginAttempt struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        *string          `json:"user_id"`
	Email         string           `json:"email"`
	IpAddress     *string          `json:"ip_address"`
	UserAgent     *string          `json:"user_agent"`
	Success       bool             `json:"success"`
	FailureReason *string          `json:"failure_reason"`
	AttemptedAt   pgtype.Timestamp `json:"attempted_at"`
}

type Notification struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	RecipientID    string           `json:"recipient_id"`
	Type           string           `json:"type"`
	DocumentID     *string          `json:"document_id"`
	DocumentType   *string          `json:"document_type"`
	Subject        string           `json:"subject"`
	Body           string           `json:"body"`
	Sent           *bool            `json:"sent"`
	SentAt         pgtype.Timestamp `json:"sent_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type NotificationsEnhanced struct {
	ID             pgtype.UUID      `json:"id"`
	OrganizationID string           `json:"organization_id"`
	UserID         string           `json:"user_id"`
	Type           string           `json:"type"`
	Title          string           `json:"title"`
	Message        string           `json:"message"`
	RelatedID      pgtype.UUID      `json:"related_id"`
	RelatedType    *string          `json:"related_type"`
	IsRead         *bool            `json:"is_read"`
	SentViaEmail   *bool            `json:"sent_via_email"`
	EmailSentAt    pgtype.Timestamp `json:"email_sent_at"`
	Priority       *string          `json:"priority"`
	Metadata       []byte           `json:"metadata"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Organization struct {
	ID           string           `json:"id"`
	Name         string           `json:"name"`
	Slug         string           `json:"slug"`
	Description  *string          `json:"description"`
	LogoUrl      *string          `json:"logo_url"`
	PrimaryColor *string          `json:"primary_color"`
	Active       *bool            `json:"active"`
	Tier         *string          `json:"tier"`
	CreatedBy    *string          `json:"created_by"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type OrganizationDepartment struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Name           string           `json:"name"`
	Code           *string          `json:"code"`
	Description    *string          `json:"description"`
	ParentID       *string          `json:"parent_id"`
	Active         *bool            `json:"active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type OrganizationMember struct {
	ID                string           `json:"id"`
	OrganizationID    string           `json:"organization_id"`
	UserID            string           `json:"user_id"`
	Role              string           `json:"role"`
	Department        *string          `json:"department"`
	Title             *string          `json:"title"`
	Active            *bool            `json:"active"`
	InvitedAt         pgtype.Timestamp `json:"invited_at"`
	JoinedAt          pgtype.Timestamp `json:"joined_at"`
	InvitedBy         *string          `json:"invited_by"`
	CustomPermissions []byte           `json:"custom_permissions"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type OrganizationRole struct {
	ID             pgtype.UUID      `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Name           string           `json:"name"`
	Description    *string          `json:"description"`
	IsSystemRole   *bool            `json:"is_system_role"`
	Permissions    []byte           `json:"permissions"`
	Active         *bool            `json:"active"`
	CreatedBy      *string          `json:"created_by"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type OrganizationSetting struct {
	ID                       string           `json:"id"`
	OrganizationID           string           `json:"organization_id"`
	RequireDigitalSignatures *bool            `json:"require_digital_signatures"`
	DefaultApprovalChain     *string          `json:"default_approval_chain"`
	Currency                 *string          `json:"currency"`
	FiscalYearStart          *int32           `json:"fiscal_year_start"`
	EnableBudgetValidation   *bool            `json:"enable_budget_validation"`
	BudgetVarianceThreshold  pgtype.Numeric   `json:"budget_variance_threshold"`
	CreatedAt                pgtype.Timestamp `json:"created_at"`
	UpdatedAt                pgtype.Timestamp `json:"updated_at"`
}

type PasswordReset struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    string           `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	UsedAt    pgtype.Timestamp `json:"used_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type PaymentVoucher struct {
	ID              string           `json:"id"`
	OrganizationID  string           `json:"organization_id"`
	VoucherNumber   string           `json:"voucher_number"`
	VendorID        string           `json:"vendor_id"`
	InvoiceNumber   *string          `json:"invoice_number"`
	Status          *string          `json:"status"`
	Amount          pgtype.Numeric   `json:"amount"`
	Currency        *string          `json:"currency"`
	PaymentMethod   *string          `json:"payment_method"`
	GlCode          *string          `json:"gl_code"`
	Description     *string          `json:"description"`
	ApprovalStage   *int32           `json:"approval_stage"`
	ApprovalHistory []byte           `json:"approval_history"`
	LinkedPo        *string          `json:"linked_po"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type PurchaseOrder struct {
	ID                string           `json:"id"`
	OrganizationID    string           `json:"organization_id"`
	PoNumber          string           `json:"po_number"`
	VendorID          string           `json:"vendor_id"`
	Status            *string          `json:"status"`
	Items             []byte           `json:"items"`
	TotalAmount       pgtype.Numeric   `json:"total_amount"`
	Currency          *string          `json:"currency"`
	DeliveryDate      pgtype.Timestamp `json:"delivery_date"`
	ApprovalStage     *int32           `json:"approval_stage"`
	ApprovalHistory   []byte           `json:"approval_history"`
	LinkedRequisition *string          `json:"linked_requisition"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type Requisition struct {
	ID                string           `json:"id"`
	OrganizationID    string           `json:"organization_id"`
	ReqNumber         string           `json:"req_number"`
	RequesterID       string           `json:"requester_id"`
	Title             string           `json:"title"`
	Description       *string          `json:"description"`
	Department        *string          `json:"department"`
	Status            *string          `json:"status"`
	Priority          *string          `json:"priority"`
	Items             []byte           `json:"items"`
	TotalAmount       pgtype.Numeric   `json:"total_amount"`
	Currency          *string          `json:"currency"`
	ApprovalStage     *int32           `json:"approval_stage"`
	ApprovalHistory   []byte           `json:"approval_history"`
	CategoryID        *string          `json:"category_id"`
	PreferredVendorID *string          `json:"preferred_vendor_id"`
	IsEstimate        *bool            `json:"is_estimate"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       string           `json:"user_id"`
	RefreshToken string           `json:"refresh_token"`
	IpAddress    *string          `json:"ip_address"`
	UserAgent    *string          `json:"user_agent"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID                    string           `json:"id"`
	Email                 string           `json:"email"`
	Name                  string           `json:"name"`
	Password              string           `json:"password"`
	Role                  string           `json:"role"`
	Active                *bool            `json:"active"`
	LastLogin             pgtype.Timestamp `json:"last_login"`
	CurrentOrganizationID *string          `json:"current_organization_id"`
	IsSuperAdmin          *bool            `json:"is_super_admin"`
	Preferences           []byte           `json:"preferences"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	DeletedAt             pgtype.Timestamp `json:"deleted_at"`
}

type UserOrganizationRole struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         string           `json:"user_id"`
	OrganizationID string           `json:"organization_id"`
	RoleID         pgtype.UUID      `json:"role_id"`
	AssignedBy     *string          `json:"assigned_by"`
	AssignedAt     pgtype.Timestamp `json:"assigned_at"`
	Active         *bool            `json:"active"`
}

type Vendor struct {
	ID          string           `json:"id"`
	VendorCode  string           `json:"vendor_code"`
	Name        string           `json:"name"`
	Email       *string          `json:"email"`
	Phone       *string          `json:"phone"`
	Country     *string          `json:"country"`
	City        *string          `json:"city"`
	BankAccount *string          `json:"bank_account"`
	TaxID       *string          `json:"tax_id"`
	Active      *bool            `json:"active"`
	CreatedBy   *string          `json:"created_by"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Workflow struct {
	ID             pgtype.UUID      `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Name           string           `json:"name"`
	Description    *string          `json:"description"`
	DocumentType   string           `json:"document_type"`
	Stages         []byte           `json:"stages"`
	IsActive       *bool            `json:"is_active"`
	IsDefault      *bool            `json:"is_default"`
	CreatedBy      *string          `json:"created_by"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
