// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountLockout struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    string           `json:"user_id"`
	Email     string           `json:"email"`
	IpAddress *string          `json:"ip_address"`
	Reason    string           `json:"reason"`
	LockedAt  pgtype.Timestamp `json:"locked_at"`
	UnlocksAt pgtype.Timestamp `json:"unlocks_at"`
	Active    *bool            `json:"active"`
}

type AuditLog struct {
	ID           string           `json:"id"`
	DocumentID   string           `json:"document_id"`
	DocumentType string           `json:"document_type"`
	UserID       string           `json:"user_id"`
	Action       string           `json:"action"`
	Changes      []byte           `json:"changes"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Budget struct {
	ID              string           `json:"id"`
	OrganizationID  string           `json:"organization_id"`
	OwnerID         string           `json:"owner_id"`
	BudgetCode      string           `json:"budget_code"`
	Department      *string          `json:"department"`
	DepartmentID    *string          `json:"department_id"`
	Status          *string          `json:"status"`
	FiscalYear      *string          `json:"fiscal_year"`
	TotalBudget     pgtype.Numeric   `json:"total_budget"`
	AllocatedAmount pgtype.Numeric   `json:"allocated_amount"`
	RemainingAmount pgtype.Numeric   `json:"remaining_amount"`
	ApprovalStage   *int32           `json:"approval_stage"`
	ApprovalHistory []byte           `json:"approval_history"`
	Name            *string          `json:"name"`
	Description     *string          `json:"description"`
	Currency        *string          `json:"currency"`
	CreatedBy       *string          `json:"created_by"`
	Items           []byte           `json:"items"`
	ActionHistory   []byte           `json:"action_history"`
	Metadata        []byte           `json:"metadata"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type Category struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Name           string           `json:"name"`
	Description    *string          `json:"description"`
	Active         *bool            `json:"active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type CategoryBudgetCode struct {
	ID         string           `json:"id"`
	CategoryID string           `json:"category_id"`
	BudgetCode string           `json:"budget_code"`
	Active     *bool            `json:"active"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

// Unified document table for all business document types
type Document struct {
	ID             pgtype.UUID      `json:"id"`
	OrganizationID string           `json:"organization_id"`
	DocumentType   string           `json:"document_type"`
	DocumentNumber string           `json:"document_number"`
	Title          string           `json:"title"`
	Description    *string          `json:"description"`
	Status         string           `json:"status"`
	Amount         pgtype.Numeric   `json:"amount"`
	Currency       *string          `json:"currency"`
	Department     *string          `json:"department"`
	CreatedBy      string           `json:"created_by"`
	UpdatedBy      *string          `json:"updated_by"`
	WorkflowID     pgtype.UUID      `json:"workflow_id"`
	Data           []byte           `json:"data"`
	Metadata       []byte           `json:"metadata"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type EmailVerification struct {
	ID         pgtype.UUID      `json:"id"`
	UserID     string           `json:"user_id"`
	Email      string           `json:"email"`
	Token      string           `json:"token"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	VerifiedAt pgtype.Timestamp `json:"verified_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type FeatureFlag struct {
	ID               pgtype.UUID      `json:"id"`
	Name             string           `json:"name"`
	Description      *string          `json:"description"`
	PlanRequirements []byte           `json:"plan_requirements"`
	IsTrialAllowed   *bool            `json:"is_trial_allowed"`
	IsEnterpriseOnly *bool            `json:"is_enterprise_only"`
	IsActive         *bool            `json:"is_active"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type GoodsReceivedNote struct {
	ID                string           `json:"id"`
	OrganizationID    string           `json:"organization_id"`
	DocumentNumber    string           `json:"document_number"`
	PoDocumentNumber  *string          `json:"po_document_number"`
	Status            *string          `json:"status"`
	ReceivedDate      pgtype.Timestamp `json:"received_date"`
	ReceivedBy        *string          `json:"received_by"`
	Items             []byte           `json:"items"`
	QualityIssues     []byte           `json:"quality_issues"`
	ApprovalStage     *int32           `json:"approval_stage"`
	ApprovalHistory   []byte           `json:"approval_history"`
	CreatedBy         *string          `json:"created_by"`
	OwnerID           *string          `json:"owner_id"`
	WarehouseLocation *string          `json:"warehouse_location"`
	Notes             *string          `json:"notes"`
	StageName         *string          `json:"stage_name"`
	ApprovedBy        *string          `json:"approved_by"`
	AutomationUsed    *bool            `json:"automation_used"`
	AutoCreatedPv     []byte           `json:"auto_created_pv"`
	ActionHistory     []byte           `json:"action_history"`
	Metadata          []byte           `json:"metadata"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type LoginAttempt struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        *string          `json:"user_id"`
	Email         string           `json:"email"`
	IpAddress     *string          `json:"ip_address"`
	UserAgent     *string          `json:"user_agent"`
	Success       bool             `json:"success"`
	FailureReason *string          `json:"failure_reason"`
	AttemptedAt   pgtype.Timestamp `json:"attempted_at"`
}

type Notification struct {
	ID                 pgtype.UUID      `json:"id"`
	OrganizationID     string           `json:"organization_id"`
	RecipientID        string           `json:"recipient_id"`
	Type               string           `json:"type"`
	DocumentID         *string          `json:"document_id"`
	DocumentType       *string          `json:"document_type"`
	Subject            string           `json:"subject"`
	Body               string           `json:"body"`
	Sent               *bool            `json:"sent"`
	SentAt             pgtype.Timestamp `json:"sent_at"`
	EntityID           *string          `json:"entity_id"`
	EntityType         *string          `json:"entity_type"`
	EntityNumber       *string          `json:"entity_number"`
	RelatedUserID      *string          `json:"related_user_id"`
	RelatedUserName    *string          `json:"related_user_name"`
	IsRead             *bool            `json:"is_read"`
	ReadAt             pgtype.Timestamp `json:"read_at"`
	ActionTaken        *bool            `json:"action_taken"`
	ActionTakenAt      pgtype.Timestamp `json:"action_taken_at"`
	Importance         *string          `json:"importance"`
	QuickAction        []byte           `json:"quick_action"`
	ReassignmentReason *string          `json:"reassignment_reason"`
	Message            *string          `json:"message"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type Organization struct {
	ID                   string           `json:"id"`
	Name                 string           `json:"name"`
	Slug                 string           `json:"slug"`
	Description          *string          `json:"description"`
	LogoUrl              *string          `json:"logo_url"`
	PrimaryColor         *string          `json:"primary_color"`
	Active               *bool            `json:"active"`
	Tier                 *string          `json:"tier"`
	CreatedBy            *string          `json:"created_by"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	TrialStartDate       pgtype.Timestamp `json:"trial_start_date"`
	TrialEndDate         pgtype.Timestamp `json:"trial_end_date"`
	CurrentPlanID        pgtype.UUID      `json:"current_plan_id"`
	SubscriptionStatus   *string          `json:"subscription_status"`
	BillingCycleStart    pgtype.Timestamp `json:"billing_cycle_start"`
	BillingCycleEnd      pgtype.Timestamp `json:"billing_cycle_end"`
	GracePeriodEndsAt    pgtype.Timestamp `json:"grace_period_ends_at"`
	MaxUsersAllowed      *int32           `json:"max_users_allowed"`
	SubscriptionMetadata []byte           `json:"subscription_metadata"`
}

// Organization departments with manager name support
type OrganizationDepartment struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Name           string           `json:"name"`
	Code           *string          `json:"code"`
	Description    *string          `json:"description"`
	ParentID       *string          `json:"parent_id"`
	ManagerName    *string          `json:"manager_name"`
	Active         *bool            `json:"active"`
	IsActive       *bool            `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type OrganizationMember struct {
	ID                string           `json:"id"`
	OrganizationID    string           `json:"organization_id"`
	UserID            string           `json:"user_id"`
	Role              string           `json:"role"`
	Department        *string          `json:"department"`
	DepartmentID      *string          `json:"department_id"`
	Title             *string          `json:"title"`
	Active            *bool            `json:"active"`
	InvitedAt         pgtype.Timestamp `json:"invited_at"`
	JoinedAt          pgtype.Timestamp `json:"joined_at"`
	InvitedBy         *string          `json:"invited_by"`
	CustomPermissions []byte           `json:"custom_permissions"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type OrganizationRole struct {
	ID             pgtype.UUID      `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Name           string           `json:"name"`
	Description    *string          `json:"description"`
	IsSystemRole   *bool            `json:"is_system_role"`
	Permissions    []byte           `json:"permissions"`
	Active         *bool            `json:"active"`
	CreatedBy      *string          `json:"created_by"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type OrganizationSetting struct {
	ID                       string           `json:"id"`
	OrganizationID           string           `json:"organization_id"`
	RequireDigitalSignatures *bool            `json:"require_digital_signatures"`
	DefaultApprovalChain     *string          `json:"default_approval_chain"`
	Currency                 *string          `json:"currency"`
	FiscalYearStart          *int32           `json:"fiscal_year_start"`
	EnableBudgetValidation   *bool            `json:"enable_budget_validation"`
	BudgetVarianceThreshold  pgtype.Numeric   `json:"budget_variance_threshold"`
	CreatedAt                pgtype.Timestamp `json:"created_at"`
	UpdatedAt                pgtype.Timestamp `json:"updated_at"`
}

type OrganizationSubscription struct {
	ID                   pgtype.UUID      `json:"id"`
	OrganizationID       string           `json:"organization_id"`
	PlanID               pgtype.UUID      `json:"plan_id"`
	StripeSubscriptionID *string          `json:"stripe_subscription_id"`
	Status               string           `json:"status"`
	CurrentPeriodStart   pgtype.Timestamp `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamp `json:"current_period_end"`
	CancelAtPeriodEnd    *bool            `json:"cancel_at_period_end"`
	PaymentFailedCount   *int32           `json:"payment_failed_count"`
	LastPaymentFailedAt  pgtype.Timestamp `json:"last_payment_failed_at"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

type OrganizationSubscriptionDetail struct {
	OrganizationID       string           `json:"organization_id"`
	OrganizationName     string           `json:"organization_name"`
	SubscriptionStatus   *string          `json:"subscription_status"`
	TrialStartDate       pgtype.Timestamp `json:"trial_start_date"`
	TrialEndDate         pgtype.Timestamp `json:"trial_end_date"`
	GracePeriodEndsAt    pgtype.Timestamp `json:"grace_period_ends_at"`
	MaxUsersAllowed      *int32           `json:"max_users_allowed"`
	PlanName             *string          `json:"plan_name"`
	PlanSlug             *string          `json:"plan_slug"`
	PriceMonthly         pgtype.Numeric   `json:"price_monthly"`
	PriceYearly          pgtype.Numeric   `json:"price_yearly"`
	PlanFeatures         []byte           `json:"plan_features"`
	PlanMaxUsers         *int32           `json:"plan_max_users"`
	StripeSubscriptionID *string          `json:"stripe_subscription_id"`
	CurrentPeriodStart   pgtype.Timestamp `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamp `json:"current_period_end"`
	CancelAtPeriodEnd    *bool            `json:"cancel_at_period_end"`
	PaymentFailedCount   *int32           `json:"payment_failed_count"`
	LastPaymentFailedAt  pgtype.Timestamp `json:"last_payment_failed_at"`
	TrialDaysRemaining   int32            `json:"trial_days_remaining"`
	TrialExpired         bool             `json:"trial_expired"`
	InGracePeriod        bool             `json:"in_grace_period"`
}

type PasswordReset struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    string           `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	UsedAt    pgtype.Timestamp `json:"used_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type PaymentVoucher struct {
	ID                        string           `json:"id"`
	OrganizationID            string           `json:"organization_id"`
	DocumentNumber            string           `json:"document_number"`
	VendorID                  string           `json:"vendor_id"`
	InvoiceNumber             *string          `json:"invoice_number"`
	Status                    *string          `json:"status"`
	Amount                    pgtype.Numeric   `json:"amount"`
	Currency                  *string          `json:"currency"`
	PaymentMethod             *string          `json:"payment_method"`
	GlCode                    *string          `json:"gl_code"`
	Description               *string          `json:"description"`
	ApprovalStage             *int32           `json:"approval_stage"`
	ApprovalHistory           []byte           `json:"approval_history"`
	LinkedPo                  *string          `json:"linked_po"`
	Title                     *string          `json:"title"`
	Department                *string          `json:"department"`
	DepartmentID              *string          `json:"department_id"`
	Priority                  *string          `json:"priority"`
	RequestedByName           *string          `json:"requested_by_name"`
	RequestedDate             pgtype.Timestamp `json:"requested_date"`
	SubmittedAt               pgtype.Timestamp `json:"submitted_at"`
	ApprovedAt                pgtype.Timestamp `json:"approved_at"`
	PaidDate                  pgtype.Timestamp `json:"paid_date"`
	PaymentDueDate            pgtype.Timestamp `json:"payment_due_date"`
	BudgetCode                *string          `json:"budget_code"`
	CostCenter                *string          `json:"cost_center"`
	ProjectCode               *string          `json:"project_code"`
	TaxAmount                 pgtype.Numeric   `json:"tax_amount"`
	WithholdingTaxAmount      pgtype.Numeric   `json:"withholding_tax_amount"`
	PaidAmount                pgtype.Numeric   `json:"paid_amount"`
	SourcePurchaseOrderNumber *string          `json:"source_purchase_order_number"`
	SourceRequisitionNumber   *string          `json:"source_requisition_number"`
	BankDetails               []byte           `json:"bank_details"`
	Items                     []byte           `json:"items"`
	CreatedBy                 *string          `json:"created_by"`
	OwnerID                   *string          `json:"owner_id"`
	ActionHistory             []byte           `json:"action_history"`
	Metadata                  []byte           `json:"metadata"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
	UpdatedAt                 pgtype.Timestamp `json:"updated_at"`
}

type PurchaseOrder struct {
	ID                      string           `json:"id"`
	OrganizationID          string           `json:"organization_id"`
	DocumentNumber          string           `json:"document_number"`
	VendorID                *string          `json:"vendor_id"`
	Status                  *string          `json:"status"`
	Items                   []byte           `json:"items"`
	TotalAmount             pgtype.Numeric   `json:"total_amount"`
	Currency                *string          `json:"currency"`
	DeliveryDate            pgtype.Timestamp `json:"delivery_date"`
	ApprovalStage           *int32           `json:"approval_stage"`
	ApprovalHistory         []byte           `json:"approval_history"`
	LinkedRequisition       *string          `json:"linked_requisition"`
	Description             *string          `json:"description"`
	Department              *string          `json:"department"`
	DepartmentID            *string          `json:"department_id"`
	GlCode                  *string          `json:"gl_code"`
	Title                   *string          `json:"title"`
	Priority                *string          `json:"priority"`
	Subtotal                pgtype.Numeric   `json:"subtotal"`
	Tax                     pgtype.Numeric   `json:"tax"`
	Total                   pgtype.Numeric   `json:"total"`
	BudgetCode              *string          `json:"budget_code"`
	CostCenter              *string          `json:"cost_center"`
	ProjectCode             *string          `json:"project_code"`
	RequiredByDate          pgtype.Timestamp `json:"required_by_date"`
	SourceRequisitionNumber *string          `json:"source_requisition_number"`
	SourceRequisitionID     *string          `json:"source_requisition_id"`
	CreatedBy               *string          `json:"created_by"`
	OwnerID                 *string          `json:"owner_id"`
	ActionHistory           []byte           `json:"action_history"`
	Metadata                []byte           `json:"metadata"`
	AutomationUsed          *bool            `json:"automation_used"`
	AutoCreatedGrn          []byte           `json:"auto_created_grn"`
	CreatedAt               pgtype.Timestamp `json:"created_at"`
	UpdatedAt               pgtype.Timestamp `json:"updated_at"`
}

type Requisition struct {
	ID                string           `json:"id"`
	OrganizationID    string           `json:"organization_id"`
	DocumentNumber    string           `json:"document_number"`
	RequesterID       string           `json:"requester_id"`
	Title             string           `json:"title"`
	Description       *string          `json:"description"`
	Department        *string          `json:"department"`
	DepartmentID      *string          `json:"department_id"`
	Status            *string          `json:"status"`
	Priority          *string          `json:"priority"`
	Items             []byte           `json:"items"`
	TotalAmount       pgtype.Numeric   `json:"total_amount"`
	Currency          *string          `json:"currency"`
	ApprovalStage     *int32           `json:"approval_stage"`
	ApprovalHistory   []byte           `json:"approval_history"`
	CategoryID        *string          `json:"category_id"`
	PreferredVendorID *string          `json:"preferred_vendor_id"`
	IsEstimate        *bool            `json:"is_estimate"`
	RequiredByDate    pgtype.Timestamp `json:"required_by_date"`
	CostCenter        *string          `json:"cost_center"`
	ProjectCode       *string          `json:"project_code"`
	CreatedBy         *string          `json:"created_by"`
	CreatedByName     *string          `json:"created_by_name"`
	CreatedByRole     *string          `json:"created_by_role"`
	Metadata          []byte           `json:"metadata"`
	AutomationUsed    *bool            `json:"automation_used"`
	AutoCreatedPo     []byte           `json:"auto_created_po"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	// JSON array of action history entries for timeline display
	ActionHistory []byte `json:"action_history"`
}

type Session struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       string           `json:"user_id"`
	RefreshToken string           `json:"refresh_token"`
	IpAddress    *string          `json:"ip_address"`
	UserAgent    *string          `json:"user_agent"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// Tracks individual approvals per workflow stage for multiple approval support
type StageApprovalRecord struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	WorkflowTaskID string           `json:"workflow_task_id"`
	StageNumber    int32            `json:"stage_number"`
	ApproverID     string           `json:"approver_id"`
	ApproverName   string           `json:"approver_name"`
	ApproverRole   string           `json:"approver_role"`
	Action         string           `json:"action"`
	Comments       *string          `json:"comments"`
	Signature      *string          `json:"signature"`
	ApprovedAt     pgtype.Timestamp `json:"approved_at"`
	IpAddress      *string          `json:"ip_address"`
	UserAgent      *string          `json:"user_agent"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type SubscriptionAuditLog struct {
	ID             pgtype.UUID      `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Action         string           `json:"action"`
	OldPlanID      pgtype.UUID      `json:"old_plan_id"`
	NewPlanID      pgtype.UUID      `json:"new_plan_id"`
	OldStatus      *string          `json:"old_status"`
	NewStatus      *string          `json:"new_status"`
	Metadata       []byte           `json:"metadata"`
	PerformedBy    *string          `json:"performed_by"`
	PerformedAt    pgtype.Timestamp `json:"performed_at"`
}

type SubscriptionPlan struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Slug         string           `json:"slug"`
	Description  *string          `json:"description"`
	PriceMonthly pgtype.Numeric   `json:"price_monthly"`
	PriceYearly  pgtype.Numeric   `json:"price_yearly"`
	Features     []byte           `json:"features"`
	MaxUsers     *int32           `json:"max_users"`
	IsActive     *bool            `json:"is_active"`
	SortOrder    *int32           `json:"sort_order"`
	Metadata     []byte           `json:"metadata"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// Tracks round-robin task assignment history for fair distribution
type TaskAssignmentHistory struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Role           string           `json:"role"`
	AssignedUserID string           `json:"assigned_user_id"`
	AssignedAt     pgtype.Timestamp `json:"assigned_at"`
}

type User struct {
	ID                    string           `json:"id"`
	Email                 string           `json:"email"`
	Name                  string           `json:"name"`
	Password              string           `json:"password"`
	Role                  string           `json:"role"`
	Active                *bool            `json:"active"`
	LastLogin             pgtype.Timestamp `json:"last_login"`
	CurrentOrganizationID *string          `json:"current_organization_id"`
	IsSuperAdmin          *bool            `json:"is_super_admin"`
	Preferences           []byte           `json:"preferences"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	DeletedAt             pgtype.Timestamp `json:"deleted_at"`
}

type UserOrganizationRole struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         string           `json:"user_id"`
	OrganizationID string           `json:"organization_id"`
	RoleID         pgtype.UUID      `json:"role_id"`
	AssignedBy     *string          `json:"assigned_by"`
	AssignedAt     pgtype.Timestamp `json:"assigned_at"`
	Active         *bool            `json:"active"`
}

// Organization-scoped vendors for multi-tenant security
type Vendor struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	VendorCode     string           `json:"vendor_code"`
	Name           string           `json:"name"`
	Email          *string          `json:"email"`
	Phone          *string          `json:"phone"`
	Country        *string          `json:"country"`
	City           *string          `json:"city"`
	BankAccount    *string          `json:"bank_account"`
	TaxID          *string          `json:"tax_id"`
	Active         *bool            `json:"active"`
	CreatedBy      *string          `json:"created_by"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

// Enhanced workflow definitions with frontend compatibility
type Workflow struct {
	ID             pgtype.UUID      `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Name           string           `json:"name"`
	Description    *string          `json:"description"`
	DocumentType   string           `json:"document_type"`
	EntityType     string           `json:"entity_type"`
	Version        *int32           `json:"version"`
	Stages         []byte           `json:"stages"`
	Conditions     []byte           `json:"conditions"`
	IsActive       *bool            `json:"is_active"`
	IsDefault      *bool            `json:"is_default"`
	CreatedBy      *string          `json:"created_by"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

// Tracks workflow execution for specific entities
type WorkflowAssignment struct {
	ID              string           `json:"id"`
	OrganizationID  string           `json:"organization_id"`
	EntityID        string           `json:"entity_id"`
	EntityType      string           `json:"entity_type"`
	WorkflowID      pgtype.UUID      `json:"workflow_id"`
	WorkflowVersion int32            `json:"workflow_version"`
	CurrentStage    *int32           `json:"current_stage"`
	Status          *string          `json:"status"`
	StageHistory    []byte           `json:"stage_history"`
	AssignedAt      pgtype.Timestamp `json:"assigned_at"`
	AssignedBy      string           `json:"assigned_by"`
	CompletedAt     pgtype.Timestamp `json:"completed_at"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

// Default workflow mappings for entity types per organization
type WorkflowDefault struct {
	ID                     string           `json:"id"`
	OrganizationID         string           `json:"organization_id"`
	EntityType             string           `json:"entity_type"`
	DefaultWorkflowID      pgtype.UUID      `json:"default_workflow_id"`
	DefaultWorkflowVersion int32            `json:"default_workflow_version"`
	SetBy                  string           `json:"set_by"`
	SetAt                  pgtype.Timestamp `json:"set_at"`
}

// Individual approval tasks within workflow assignments with concurrency control
type WorkflowTask struct {
	ID                   string           `json:"id"`
	OrganizationID       string           `json:"organization_id"`
	WorkflowAssignmentID string           `json:"workflow_assignment_id"`
	EntityID             string           `json:"entity_id"`
	EntityType           string           `json:"entity_type"`
	StageNumber          int32            `json:"stage_number"`
	StageName            string           `json:"stage_name"`
	AssignmentType       *string          `json:"assignment_type"`
	AssignedRole         *string          `json:"assigned_role"`
	AssignedUserID       *string          `json:"assigned_user_id"`
	Status               *string          `json:"status"`
	Priority             *string          `json:"priority"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	ClaimedAt            pgtype.Timestamp `json:"claimed_at"`
	ClaimedBy            *string          `json:"claimed_by"`
	CompletedAt          pgtype.Timestamp `json:"completed_at"`
	DueDate              pgtype.Timestamp `json:"due_date"`
	Version              int32            `json:"version"`
	UpdatedBy            *string          `json:"updated_by"`
	ClaimExpiry          pgtype.Timestamp `json:"claim_expiry"`
}
