// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserRole = `-- name: AssignUserRole :one
INSERT INTO user_organization_roles (
    user_id, organization_id, role_id, assigned_by
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, organization_id, role_id, assigned_by, assigned_at, active
`

// User role assignments
func (q *Queries) AssignUserRole(ctx context.Context, userID string, organizationID string, roleID pgtype.UUID, assignedBy *string) (UserOrganizationRole, error) {
	row := q.db.QueryRow(ctx, assignUserRole,
		userID,
		organizationID,
		roleID,
		assignedBy,
	)
	var i UserOrganizationRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.RoleID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.Active,
	)
	return i, err
}

const countCustomRoles = `-- name: CountCustomRoles :one
SELECT COUNT(*) FROM organization_roles 
WHERE organization_id = $1 AND is_system_role = false AND active = true
`

func (q *Queries) CountCustomRoles(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomRoles, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationRoles = `-- name: CountOrganizationRoles :one
SELECT COUNT(*) FROM organization_roles 
WHERE organization_id = $1 AND active = true
`

func (q *Queries) CountOrganizationRoles(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationRoles, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganizationRole = `-- name: CreateOrganizationRole :one

INSERT INTO organization_roles (
    organization_id, name, description, is_system_role, permissions, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at
`

type CreateOrganizationRoleParams struct {
	OrganizationID string  `json:"organization_id"`
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	IsSystemRole   *bool   `json:"is_system_role"`
	Permissions    []byte  `json:"permissions"`
	CreatedBy      *string `json:"created_by"`
}

// Enhanced RBAC with custom organization roles
func (q *Queries) CreateOrganizationRole(ctx context.Context, arg CreateOrganizationRoleParams) (OrganizationRole, error) {
	row := q.db.QueryRow(ctx, createOrganizationRole,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.IsSystemRole,
		arg.Permissions,
		arg.CreatedBy,
	)
	var i OrganizationRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.IsSystemRole,
		&i.Permissions,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateOrganizationRole = `-- name: DeactivateOrganizationRole :exec
UPDATE organization_roles SET 
    active = false,
    updated_at = NOW()
WHERE id = $1 AND is_system_role = false
`

func (q *Queries) DeactivateOrganizationRole(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateOrganizationRole, id)
	return err
}

const getOrganizationRoleByID = `-- name: GetOrganizationRoleByID :one
SELECT id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at FROM organization_roles WHERE id = $1 AND active = true
`

func (q *Queries) GetOrganizationRoleByID(ctx context.Context, id pgtype.UUID) (OrganizationRole, error) {
	row := q.db.QueryRow(ctx, getOrganizationRoleByID, id)
	var i OrganizationRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.IsSystemRole,
		&i.Permissions,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationRoleByName = `-- name: GetOrganizationRoleByName :one
SELECT id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at FROM organization_roles 
WHERE organization_id = $1 AND name = $2 AND active = true
`

func (q *Queries) GetOrganizationRoleByName(ctx context.Context, organizationID string, name string) (OrganizationRole, error) {
	row := q.db.QueryRow(ctx, getOrganizationRoleByName, organizationID, name)
	var i OrganizationRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.IsSystemRole,
		&i.Permissions,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoleAssignments = `-- name: GetUserRoleAssignments :many
SELECT uor.id, uor.user_id, uor.organization_id, uor.role_id, uor.assigned_by, uor.assigned_at, uor.active, org_roles.name as role_name, org_roles.description as role_description
FROM user_organization_roles uor
INNER JOIN organization_roles org_roles ON uor.role_id = org_roles.id
WHERE uor.user_id = $1 AND uor.organization_id = $2 AND uor.active = true
`

type GetUserRoleAssignmentsRow struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          string           `json:"user_id"`
	OrganizationID  string           `json:"organization_id"`
	RoleID          pgtype.UUID      `json:"role_id"`
	AssignedBy      *string          `json:"assigned_by"`
	AssignedAt      pgtype.Timestamp `json:"assigned_at"`
	Active          *bool            `json:"active"`
	RoleName        string           `json:"role_name"`
	RoleDescription *string          `json:"role_description"`
}

func (q *Queries) GetUserRoleAssignments(ctx context.Context, userID string, organizationID string) ([]GetUserRoleAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, getUserRoleAssignments, userID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRoleAssignmentsRow{}
	for rows.Next() {
		var i GetUserRoleAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationID,
			&i.RoleID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.Active,
			&i.RoleName,
			&i.RoleDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT org_roles.id, org_roles.organization_id, org_roles.name, org_roles.description, org_roles.is_system_role, org_roles.permissions, org_roles.active, org_roles.created_by, org_roles.created_at, org_roles.updated_at FROM organization_roles org_roles
INNER JOIN user_organization_roles uor ON org_roles.id = uor.role_id
WHERE uor.user_id = $1 AND uor.organization_id = $2 AND uor.active = true AND org_roles.active = true
`

func (q *Queries) GetUserRoles(ctx context.Context, userID string, organizationID string) ([]OrganizationRole, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationRole{}
	for rows.Next() {
		var i OrganizationRole
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.IsSystemRole,
			&i.Permissions,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomRoles = `-- name: ListCustomRoles :many
SELECT id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at FROM organization_roles 
WHERE organization_id = $1 AND is_system_role = false AND active = true
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListCustomRoles(ctx context.Context, organizationID string, limit int32, offset int32) ([]OrganizationRole, error) {
	rows, err := q.db.Query(ctx, listCustomRoles, organizationID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationRole{}
	for rows.Next() {
		var i OrganizationRole
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.IsSystemRole,
			&i.Permissions,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationRoles = `-- name: ListOrganizationRoles :many
SELECT id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at FROM organization_roles 
WHERE organization_id = $1 AND active = true
ORDER BY is_system_role DESC, name ASC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListOrganizationRoles(ctx context.Context, organizationID string, limit int32, offset int32) ([]OrganizationRole, error) {
	rows, err := q.db.Query(ctx, listOrganizationRoles, organizationID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationRole{}
	for rows.Next() {
		var i OrganizationRole
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.IsSystemRole,
			&i.Permissions,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemRoles = `-- name: ListSystemRoles :many
SELECT id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at FROM organization_roles 
WHERE organization_id = $1 AND is_system_role = true AND active = true
ORDER BY name ASC
`

func (q *Queries) ListSystemRoles(ctx context.Context, organizationID string) ([]OrganizationRole, error) {
	rows, err := q.db.Query(ctx, listSystemRoles, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationRole{}
	for rows.Next() {
		var i OrganizationRole
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.IsSystemRole,
			&i.Permissions,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRole = `-- name: ListUsersWithRole :many
SELECT u.id, u.email, u.name, u.password, u.role, u.active, u.last_login, u.current_organization_id, u.is_super_admin, u.preferences, u.created_at, u.updated_at, u.deleted_at, uor.assigned_at FROM users u
INNER JOIN user_organization_roles uor ON u.id = uor.user_id
WHERE uor.organization_id = $1 AND uor.role_id = $2 AND uor.active = true
ORDER BY u.name
LIMIT $3 OFFSET $4
`

type ListUsersWithRoleRow struct {
	ID                    string           `json:"id"`
	Email                 string           `json:"email"`
	Name                  string           `json:"name"`
	Password              string           `json:"password"`
	Role                  string           `json:"role"`
	Active                *bool            `json:"active"`
	LastLogin             pgtype.Timestamp `json:"last_login"`
	CurrentOrganizationID *string          `json:"current_organization_id"`
	IsSuperAdmin          *bool            `json:"is_super_admin"`
	Preferences           []byte           `json:"preferences"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	DeletedAt             pgtype.Timestamp `json:"deleted_at"`
	AssignedAt            pgtype.Timestamp `json:"assigned_at"`
}

func (q *Queries) ListUsersWithRole(ctx context.Context, organizationID string, roleID pgtype.UUID, limit int32, offset int32) ([]ListUsersWithRoleRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithRole,
		organizationID,
		roleID,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithRoleRow{}
	for rows.Next() {
		var i ListUsersWithRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Password,
			&i.Role,
			&i.Active,
			&i.LastLogin,
			&i.CurrentOrganizationID,
			&i.IsSuperAdmin,
			&i.Preferences,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllUserRoles = `-- name: RemoveAllUserRoles :exec
UPDATE user_organization_roles SET 
    active = false
WHERE user_id = $1 AND organization_id = $2
`

func (q *Queries) RemoveAllUserRoles(ctx context.Context, userID string, organizationID string) error {
	_, err := q.db.Exec(ctx, removeAllUserRoles, userID, organizationID)
	return err
}

const removeUserRole = `-- name: RemoveUserRole :exec
UPDATE user_organization_roles SET 
    active = false
WHERE user_id = $1 AND organization_id = $2 AND role_id = $3
`

func (q *Queries) RemoveUserRole(ctx context.Context, userID string, organizationID string, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeUserRole, userID, organizationID, roleID)
	return err
}

const updateOrganizationRole = `-- name: UpdateOrganizationRole :one
UPDATE organization_roles SET 
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    permissions = COALESCE($4, permissions),
    updated_at = NOW()
WHERE id = $1 AND is_system_role = false
RETURNING id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at
`

func (q *Queries) UpdateOrganizationRole(ctx context.Context, iD pgtype.UUID, name string, description *string, permissions []byte) (OrganizationRole, error) {
	row := q.db.QueryRow(ctx, updateOrganizationRole,
		iD,
		name,
		description,
		permissions,
	)
	var i OrganizationRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.IsSystemRole,
		&i.Permissions,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
