// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_subscription_management.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkOrganizationFeatureAccess = `-- name: CheckOrganizationFeatureAccess :one
SELECT organization_has_feature($1, $2) as has_access
`

func (q *Queries) CheckOrganizationFeatureAccess(ctx context.Context, orgID string, featureName string) (bool, error) {
	row := q.db.QueryRow(ctx, checkOrganizationFeatureAccess, orgID, featureName)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const checkOrganizationUserLimit = `-- name: CheckOrganizationUserLimit :one
SELECT 
    CASE 
        WHEN sp.max_users = -1 THEN true  -- Unlimited
        WHEN COUNT(u.id) < o.max_users_allowed THEN true
        ELSE false
    END as within_limit
FROM organizations o
LEFT JOIN subscription_plans sp ON o.current_plan_id = sp.id
LEFT JOIN users u ON u.organization_id = o.id AND u.deleted_at IS NULL
WHERE o.id = $1
GROUP BY o.id, o.max_users_allowed, sp.max_users
`

func (q *Queries) CheckOrganizationUserLimit(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, checkOrganizationUserLimit, id)
	var within_limit bool
	err := row.Scan(&within_limit)
	return within_limit, err
}

const createFeatureFlag = `-- name: CreateFeatureFlag :one
INSERT INTO subscription_feature_requirements (
    name, description, plan_requirements, is_trial_allowed, is_enterprise_only
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING name, description, plan_requirements, is_trial_allowed, is_enterprise_only, created_at, updated_at
`

func (q *Queries) CreateFeatureFlag(ctx context.Context, name string, description *string, planRequirements []byte, isTrialAllowed bool, isEnterpriseOnly bool) (SubscriptionFeatureRequirement, error) {
	row := q.db.QueryRow(ctx, createFeatureFlag,
		name,
		description,
		planRequirements,
		isTrialAllowed,
		isEnterpriseOnly,
	)
	var i SubscriptionFeatureRequirement
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.PlanRequirements,
		&i.IsTrialAllowed,
		&i.IsEnterpriseOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationSubscription = `-- name: CreateOrganizationSubscription :one
INSERT INTO organization_subscriptions (
    organization_id, plan_id, stripe_subscription_id, status,
    current_period_start, current_period_end, cancel_at_period_end
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, organization_id, plan_id, stripe_subscription_id, status, current_period_start, current_period_end, cancel_at_period_end, payment_failed_count, last_payment_failed_at, created_at, updated_at
`

type CreateOrganizationSubscriptionParams struct {
	OrganizationID       string             `json:"organization_id"`
	PlanID               pgtype.UUID        `json:"plan_id"`
	StripeSubscriptionID *string            `json:"stripe_subscription_id"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CancelAtPeriodEnd    *bool              `json:"cancel_at_period_end"`
}

func (q *Queries) CreateOrganizationSubscription(ctx context.Context, arg CreateOrganizationSubscriptionParams) (OrganizationSubscription, error) {
	row := q.db.QueryRow(ctx, createOrganizationSubscription,
		arg.OrganizationID,
		arg.PlanID,
		arg.StripeSubscriptionID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
	)
	var i OrganizationSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.PaymentFailedCount,
		&i.LastPaymentFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscriptionAuditLog = `-- name: CreateSubscriptionAuditLog :one

INSERT INTO subscription_audit_logs (
    organization_id, action, old_plan_id, new_plan_id, 
    old_status, new_status, metadata, performed_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, organization_id, action, old_plan_id, new_plan_id, old_status, new_status, metadata, performed_by, performed_at
`

type CreateSubscriptionAuditLogParams struct {
	OrganizationID string      `json:"organization_id"`
	Action         string      `json:"action"`
	OldPlanID      pgtype.UUID `json:"old_plan_id"`
	NewPlanID      pgtype.UUID `json:"new_plan_id"`
	OldStatus      *string     `json:"old_status"`
	NewStatus      *string     `json:"new_status"`
	Metadata       []byte      `json:"metadata"`
	PerformedBy    *string     `json:"performed_by"`
}

// ============================================================================
// AUDIT LOG QUERIES
// ============================================================================
func (q *Queries) CreateSubscriptionAuditLog(ctx context.Context, arg CreateSubscriptionAuditLogParams) (SubscriptionAuditLog, error) {
	row := q.db.QueryRow(ctx, createSubscriptionAuditLog,
		arg.OrganizationID,
		arg.Action,
		arg.OldPlanID,
		arg.NewPlanID,
		arg.OldStatus,
		arg.NewStatus,
		arg.Metadata,
		arg.PerformedBy,
	)
	var i SubscriptionAuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Action,
		&i.OldPlanID,
		&i.NewPlanID,
		&i.OldStatus,
		&i.NewStatus,
		&i.Metadata,
		&i.PerformedBy,
		&i.PerformedAt,
	)
	return i, err
}

const createSubscriptionPlan = `-- name: CreateSubscriptionPlan :one
INSERT INTO subscription_plans (
    name, slug, description, price_monthly, price_yearly, 
    features, max_users, is_active, sort_order, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, name, slug, description, price_monthly, price_yearly, features, max_users, is_active, sort_order, metadata, created_at, updated_at
`

type CreateSubscriptionPlanParams struct {
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  *string        `json:"description"`
	PriceMonthly pgtype.Numeric `json:"price_monthly"`
	PriceYearly  pgtype.Numeric `json:"price_yearly"`
	Features     []byte         `json:"features"`
	MaxUsers     *int32         `json:"max_users"`
	IsActive     *bool          `json:"is_active"`
	SortOrder    *int32         `json:"sort_order"`
	Metadata     []byte         `json:"metadata"`
}

func (q *Queries) CreateSubscriptionPlan(ctx context.Context, arg CreateSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, createSubscriptionPlan,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.PriceMonthly,
		arg.PriceYearly,
		arg.Features,
		arg.MaxUsers,
		arg.IsActive,
		arg.SortOrder,
		arg.Metadata,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.Features,
		&i.MaxUsers,
		&i.IsActive,
		&i.SortOrder,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscriptionPlan = `-- name: DeleteSubscriptionPlan :exec
UPDATE subscription_plans SET 
    is_active = false,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteSubscriptionPlan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscriptionPlan, id)
	return err
}

const extendOrganizationTrial = `-- name: ExtendOrganizationTrial :exec
SELECT extend_organization_trial($1::VARCHAR, $2::INTEGER, $3::VARCHAR)
`

func (q *Queries) ExtendOrganizationTrial(ctx context.Context, column1 string, column2 int32, column3 string) error {
	_, err := q.db.Exec(ctx, extendOrganizationTrial, column1, column2, column3)
	return err
}

const getAllFeatureFlags = `-- name: GetAllFeatureFlags :many

SELECT id, key, name, description, type, default_value, enabled, environment, category, tags, targeting, variations, last_evaluated, evaluation_count, is_archived, expires_at, created_by, updated_by, created_at, updated_at FROM feature_flags 
WHERE is_active = true 
ORDER BY name ASC
`

// ============================================================================
// FEATURE FLAGS QUERIES
// ============================================================================
func (q *Queries) GetAllFeatureFlags(ctx context.Context) ([]FeatureFlag, error) {
	rows, err := q.db.Query(ctx, getAllFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureFlag{}
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.DefaultValue,
			&i.Enabled,
			&i.Environment,
			&i.Category,
			&i.Tags,
			&i.Targeting,
			&i.Variations,
			&i.LastEvaluated,
			&i.EvaluationCount,
			&i.IsArchived,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOrganizationsWithSubscriptionStatus = `-- name: GetAllOrganizationsWithSubscriptionStatus :many

SELECT 
    o.id,
    o.name,
    o.subscription_status,
    o.trial_start_date,
    o.trial_end_date,
    o.grace_period_ends_at,
    sp.name as plan_name,
    sp.slug as plan_slug,
    os.stripe_subscription_id,
    os.payment_failed_count,
    os.last_payment_failed_at,
    CASE 
        WHEN o.subscription_status = 'trial' AND CURRENT_TIMESTAMP <= o.trial_end_date THEN
            EXTRACT(DAYS FROM o.trial_end_date - CURRENT_TIMESTAMP)::INTEGER
        ELSE 0
    END as trial_days_remaining
FROM organizations o
LEFT JOIN subscription_plans sp ON o.current_plan_id = sp.id
LEFT JOIN organization_subscriptions os ON o.id = os.organization_id
ORDER BY o.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllOrganizationsWithSubscriptionStatusRow struct {
	ID                   string             `json:"id"`
	Name                 string             `json:"name"`
	SubscriptionStatus   string             `json:"subscription_status"`
	TrialStartDate       pgtype.Timestamptz `json:"trial_start_date"`
	TrialEndDate         pgtype.Timestamptz `json:"trial_end_date"`
	GracePeriodEndsAt    pgtype.Timestamptz `json:"grace_period_ends_at"`
	PlanName             *string            `json:"plan_name"`
	PlanSlug             *string            `json:"plan_slug"`
	StripeSubscriptionID *string            `json:"stripe_subscription_id"`
	PaymentFailedCount   *int32             `json:"payment_failed_count"`
	LastPaymentFailedAt  pgtype.Timestamptz `json:"last_payment_failed_at"`
	TrialDaysRemaining   int32              `json:"trial_days_remaining"`
}

// ============================================================================
// ADMIN QUERIES
// ============================================================================
func (q *Queries) GetAllOrganizationsWithSubscriptionStatus(ctx context.Context, limit int32, offset int32) ([]GetAllOrganizationsWithSubscriptionStatusRow, error) {
	rows, err := q.db.Query(ctx, getAllOrganizationsWithSubscriptionStatus, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllOrganizationsWithSubscriptionStatusRow{}
	for rows.Next() {
		var i GetAllOrganizationsWithSubscriptionStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SubscriptionStatus,
			&i.TrialStartDate,
			&i.TrialEndDate,
			&i.GracePeriodEndsAt,
			&i.PlanName,
			&i.PlanSlug,
			&i.StripeSubscriptionID,
			&i.PaymentFailedCount,
			&i.LastPaymentFailedAt,
			&i.TrialDaysRemaining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSubscriptionPlans = `-- name: GetAllSubscriptionPlans :many

SELECT id, name, slug, description, price_monthly, price_yearly, features, max_users, is_active, sort_order, metadata, created_at, updated_at FROM subscription_plans 
WHERE is_active = true 
ORDER BY sort_order ASC
`

// ============================================================================
// SUBSCRIPTION PLANS QUERIES
// ============================================================================
func (q *Queries) GetAllSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, getAllSubscriptionPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionPlan{}
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.PriceMonthly,
			&i.PriceYearly,
			&i.Features,
			&i.MaxUsers,
			&i.IsActive,
			&i.SortOrder,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeatureFlagByName = `-- name: GetFeatureFlagByName :one
SELECT id, key, name, description, type, default_value, enabled, environment, category, tags, targeting, variations, last_evaluated, evaluation_count, is_archived, expires_at, created_by, updated_by, created_at, updated_at FROM feature_flags 
WHERE name = $1 AND is_active = true
`

func (q *Queries) GetFeatureFlagByName(ctx context.Context, name string) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, getFeatureFlagByName, name)
	var i FeatureFlag
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.DefaultValue,
		&i.Enabled,
		&i.Environment,
		&i.Category,
		&i.Tags,
		&i.Targeting,
		&i.Variations,
		&i.LastEvaluated,
		&i.EvaluationCount,
		&i.IsArchived,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeatureFlagsForPlan = `-- name: GetFeatureFlagsForPlan :many
SELECT ff.name, ff.description, ff.plan_requirements, ff.is_trial_allowed, ff.is_enterprise_only, ff.created_at, ff.updated_at FROM subscription_feature_requirements ff
WHERE (
    ff.plan_requirements ? $1
    OR ($2 = true AND ff.is_trial_allowed = true)
  )
ORDER BY ff.name ASC
`

func (q *Queries) GetFeatureFlagsForPlan(ctx context.Context, planRequirements []byte, column2 interface{}) ([]SubscriptionFeatureRequirement, error) {
	rows, err := q.db.Query(ctx, getFeatureFlagsForPlan, planRequirements, column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionFeatureRequirement{}
	for rows.Next() {
		var i SubscriptionFeatureRequirement
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.PlanRequirements,
			&i.IsTrialAllowed,
			&i.IsEnterpriseOnly,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationAuditLogs = `-- name: GetOrganizationAuditLogs :many
SELECT 
    sal.id, sal.organization_id, sal.action, sal.old_plan_id, sal.new_plan_id, sal.old_status, sal.new_status, sal.metadata, sal.performed_by, sal.performed_at,
    old_plan.name as old_plan_name,
    old_plan.slug as old_plan_slug,
    new_plan.name as new_plan_name,
    new_plan.slug as new_plan_slug
FROM subscription_audit_logs sal
LEFT JOIN subscription_plans old_plan ON sal.old_plan_id = old_plan.id
LEFT JOIN subscription_plans new_plan ON sal.new_plan_id = new_plan.id
WHERE sal.organization_id = $1
ORDER BY sal.performed_at DESC
LIMIT $2 OFFSET $3
`

type GetOrganizationAuditLogsRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID string             `json:"organization_id"`
	Action         string             `json:"action"`
	OldPlanID      pgtype.UUID        `json:"old_plan_id"`
	NewPlanID      pgtype.UUID        `json:"new_plan_id"`
	OldStatus      *string            `json:"old_status"`
	NewStatus      *string            `json:"new_status"`
	Metadata       []byte             `json:"metadata"`
	PerformedBy    *string            `json:"performed_by"`
	PerformedAt    pgtype.Timestamptz `json:"performed_at"`
	OldPlanName    *string            `json:"old_plan_name"`
	OldPlanSlug    *string            `json:"old_plan_slug"`
	NewPlanName    *string            `json:"new_plan_name"`
	NewPlanSlug    *string            `json:"new_plan_slug"`
}

func (q *Queries) GetOrganizationAuditLogs(ctx context.Context, organizationID string, limit int32, offset int32) ([]GetOrganizationAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, getOrganizationAuditLogs, organizationID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrganizationAuditLogsRow{}
	for rows.Next() {
		var i GetOrganizationAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Action,
			&i.OldPlanID,
			&i.NewPlanID,
			&i.OldStatus,
			&i.NewStatus,
			&i.Metadata,
			&i.PerformedBy,
			&i.PerformedAt,
			&i.OldPlanName,
			&i.OldPlanSlug,
			&i.NewPlanName,
			&i.NewPlanSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationPlanLimits = `-- name: GetOrganizationPlanLimits :one

SELECT 
    o.id as organization_id,
    o.max_users_allowed,
    sp.max_users as plan_max_users,
    sp.metadata as plan_metadata,
    COUNT(u.id) as current_user_count,
    CASE 
        WHEN sp.max_users = -1 THEN true  -- Unlimited
        WHEN COUNT(u.id) < o.max_users_allowed THEN true
        ELSE false
    END as can_add_users
FROM organizations o
LEFT JOIN subscription_plans sp ON o.current_plan_id = sp.id
LEFT JOIN users u ON u.organization_id = o.id AND u.deleted_at IS NULL
WHERE o.id = $1
GROUP BY o.id, o.max_users_allowed, sp.max_users, sp.metadata
`

type GetOrganizationPlanLimitsRow struct {
	OrganizationID   string `json:"organization_id"`
	MaxUsersAllowed  *int32 `json:"max_users_allowed"`
	PlanMaxUsers     *int32 `json:"plan_max_users"`
	PlanMetadata     []byte `json:"plan_metadata"`
	CurrentUserCount int64  `json:"current_user_count"`
	CanAddUsers      bool   `json:"can_add_users"`
}

// ============================================================================
// PLAN LIMITS AND ANALYTICS QUERIES
// ============================================================================
func (q *Queries) GetOrganizationPlanLimits(ctx context.Context, id string) (GetOrganizationPlanLimitsRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationPlanLimits, id)
	var i GetOrganizationPlanLimitsRow
	err := row.Scan(
		&i.OrganizationID,
		&i.MaxUsersAllowed,
		&i.PlanMaxUsers,
		&i.PlanMetadata,
		&i.CurrentUserCount,
		&i.CanAddUsers,
	)
	return i, err
}

const getOrganizationSubscription = `-- name: GetOrganizationSubscription :one
SELECT id, organization_id, plan_id, stripe_subscription_id, status, current_period_start, current_period_end, cancel_at_period_end, payment_failed_count, last_payment_failed_at, created_at, updated_at FROM organization_subscriptions 
WHERE organization_id = $1
`

func (q *Queries) GetOrganizationSubscription(ctx context.Context, organizationID string) (OrganizationSubscription, error) {
	row := q.db.QueryRow(ctx, getOrganizationSubscription, organizationID)
	var i OrganizationSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.PaymentFailedCount,
		&i.LastPaymentFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationSubscriptionDetails = `-- name: GetOrganizationSubscriptionDetails :one

SELECT organization_id, organization_name, subscription_status, trial_start_date, trial_end_date, grace_period_ends_at, max_users_allowed, plan_name, plan_slug, price_monthly, price_yearly, plan_features, plan_max_users, stripe_subscription_id, current_period_start, current_period_end, cancel_at_period_end, payment_failed_count, last_payment_failed_at, trial_days_remaining, trial_expired, in_grace_period FROM organization_subscription_details 
WHERE organization_id = $1
`

// ============================================================================
// ORGANIZATION SUBSCRIPTION QUERIES
// ============================================================================
func (q *Queries) GetOrganizationSubscriptionDetails(ctx context.Context, organizationID string) (OrganizationSubscriptionDetail, error) {
	row := q.db.QueryRow(ctx, getOrganizationSubscriptionDetails, organizationID)
	var i OrganizationSubscriptionDetail
	err := row.Scan(
		&i.OrganizationID,
		&i.OrganizationName,
		&i.SubscriptionStatus,
		&i.TrialStartDate,
		&i.TrialEndDate,
		&i.GracePeriodEndsAt,
		&i.MaxUsersAllowed,
		&i.PlanName,
		&i.PlanSlug,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.PlanFeatures,
		&i.PlanMaxUsers,
		&i.StripeSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.PaymentFailedCount,
		&i.LastPaymentFailedAt,
		&i.TrialDaysRemaining,
		&i.TrialExpired,
		&i.InGracePeriod,
	)
	return i, err
}

const getOrganizationTrialStatus = `-- name: GetOrganizationTrialStatus :one

SELECT 
    o.id as organization_id,
    o.subscription_status,
    o.trial_start_date,
    o.trial_end_date,
    o.grace_period_ends_at,
    sp.slug as plan_slug,
    sp.name as plan_name,
    CASE 
        WHEN o.subscription_status = 'trial' AND CURRENT_TIMESTAMP <= o.trial_end_date THEN
            EXTRACT(DAYS FROM o.trial_end_date - CURRENT_TIMESTAMP)::INTEGER
        ELSE 0
    END as days_remaining,
    CASE 
        WHEN o.subscription_status = 'trial' AND CURRENT_TIMESTAMP > o.trial_end_date THEN true
        ELSE false
    END as is_expired,
    CASE 
        WHEN o.subscription_status = 'trial' AND CURRENT_TIMESTAMP <= o.trial_end_date THEN true
        ELSE false
    END as is_active,
    CASE 
        WHEN o.grace_period_ends_at IS NOT NULL AND CURRENT_TIMESTAMP <= o.grace_period_ends_at THEN true
        ELSE false
    END as in_grace_period
FROM organizations o
LEFT JOIN subscription_plans sp ON o.current_plan_id = sp.id
WHERE o.id = $1
`

type GetOrganizationTrialStatusRow struct {
	OrganizationID     string             `json:"organization_id"`
	SubscriptionStatus string             `json:"subscription_status"`
	TrialStartDate     pgtype.Timestamptz `json:"trial_start_date"`
	TrialEndDate       pgtype.Timestamptz `json:"trial_end_date"`
	GracePeriodEndsAt  pgtype.Timestamptz `json:"grace_period_ends_at"`
	PlanSlug           *string            `json:"plan_slug"`
	PlanName           *string            `json:"plan_name"`
	DaysRemaining      int32              `json:"days_remaining"`
	IsExpired          bool               `json:"is_expired"`
	IsActive           bool               `json:"is_active"`
	InGracePeriod      bool               `json:"in_grace_period"`
}

// ============================================================================
// TRIAL MANAGEMENT QUERIES
// ============================================================================
func (q *Queries) GetOrganizationTrialStatus(ctx context.Context, id string) (GetOrganizationTrialStatusRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationTrialStatus, id)
	var i GetOrganizationTrialStatusRow
	err := row.Scan(
		&i.OrganizationID,
		&i.SubscriptionStatus,
		&i.TrialStartDate,
		&i.TrialEndDate,
		&i.GracePeriodEndsAt,
		&i.PlanSlug,
		&i.PlanName,
		&i.DaysRemaining,
		&i.IsExpired,
		&i.IsActive,
		&i.InGracePeriod,
	)
	return i, err
}

const getPlanDistribution = `-- name: GetPlanDistribution :many
SELECT 
    sp.name as plan_name,
    sp.slug as plan_slug,
    COUNT(o.id) as organization_count,
    ROUND(COUNT(o.id)::DECIMAL / (SELECT COUNT(*) FROM organizations) * 100, 2) as percentage
FROM subscription_plans sp
LEFT JOIN organizations o ON o.current_plan_id = sp.id
WHERE sp.is_active = true
GROUP BY sp.id, sp.name, sp.slug, sp.sort_order
ORDER BY sp.sort_order ASC
`

type GetPlanDistributionRow struct {
	PlanName          string         `json:"plan_name"`
	PlanSlug          string         `json:"plan_slug"`
	OrganizationCount int64          `json:"organization_count"`
	Percentage        pgtype.Numeric `json:"percentage"`
}

func (q *Queries) GetPlanDistribution(ctx context.Context) ([]GetPlanDistributionRow, error) {
	rows, err := q.db.Query(ctx, getPlanDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlanDistributionRow{}
	for rows.Next() {
		var i GetPlanDistributionRow
		if err := rows.Scan(
			&i.PlanName,
			&i.PlanSlug,
			&i.OrganizationCount,
			&i.Percentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentAuditLogs = `-- name: GetRecentAuditLogs :many
SELECT 
    sal.id, sal.organization_id, sal.action, sal.old_plan_id, sal.new_plan_id, sal.old_status, sal.new_status, sal.metadata, sal.performed_by, sal.performed_at,
    o.name as organization_name,
    old_plan.name as old_plan_name,
    old_plan.slug as old_plan_slug,
    new_plan.name as new_plan_name,
    new_plan.slug as new_plan_slug
FROM subscription_audit_logs sal
LEFT JOIN organizations o ON sal.organization_id = o.id
LEFT JOIN subscription_plans old_plan ON sal.old_plan_id = old_plan.id
LEFT JOIN subscription_plans new_plan ON sal.new_plan_id = new_plan.id
ORDER BY sal.performed_at DESC
LIMIT $1 OFFSET $2
`

type GetRecentAuditLogsRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   string             `json:"organization_id"`
	Action           string             `json:"action"`
	OldPlanID        pgtype.UUID        `json:"old_plan_id"`
	NewPlanID        pgtype.UUID        `json:"new_plan_id"`
	OldStatus        *string            `json:"old_status"`
	NewStatus        *string            `json:"new_status"`
	Metadata         []byte             `json:"metadata"`
	PerformedBy      *string            `json:"performed_by"`
	PerformedAt      pgtype.Timestamptz `json:"performed_at"`
	OrganizationName *string            `json:"organization_name"`
	OldPlanName      *string            `json:"old_plan_name"`
	OldPlanSlug      *string            `json:"old_plan_slug"`
	NewPlanName      *string            `json:"new_plan_name"`
	NewPlanSlug      *string            `json:"new_plan_slug"`
}

func (q *Queries) GetRecentAuditLogs(ctx context.Context, limit int32, offset int32) ([]GetRecentAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, getRecentAuditLogs, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentAuditLogsRow{}
	for rows.Next() {
		var i GetRecentAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Action,
			&i.OldPlanID,
			&i.NewPlanID,
			&i.OldStatus,
			&i.NewStatus,
			&i.Metadata,
			&i.PerformedBy,
			&i.PerformedAt,
			&i.OrganizationName,
			&i.OldPlanName,
			&i.OldPlanSlug,
			&i.NewPlanName,
			&i.NewPlanSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionAnalytics = `-- name: GetSubscriptionAnalytics :one
SELECT 
    COUNT(*) FILTER (WHERE subscription_status = 'trial') as trial_count,
    COUNT(*) FILTER (WHERE subscription_status = 'active') as active_count,
    COUNT(*) FILTER (WHERE subscription_status = 'past_due') as past_due_count,
    COUNT(*) FILTER (WHERE subscription_status = 'canceled') as canceled_count,
    COUNT(*) FILTER (WHERE subscription_status = 'expired') as expired_count,
    COUNT(*) FILTER (WHERE subscription_status = 'trial' AND trial_end_date < CURRENT_TIMESTAMP) as expired_trials,
    COUNT(*) FILTER (WHERE subscription_status = 'trial' AND trial_end_date BETWEEN CURRENT_TIMESTAMP AND CURRENT_TIMESTAMP + INTERVAL '3 days') as trials_ending_soon,
    ROUND(
        COUNT(*) FILTER (WHERE subscription_status = 'active')::DECIMAL / 
        NULLIF(COUNT(*) FILTER (WHERE subscription_status IN ('trial', 'active', 'canceled', 'expired')), 0) * 100, 
        2
    ) as conversion_rate
FROM organizations
`

type GetSubscriptionAnalyticsRow struct {
	TrialCount       int64          `json:"trial_count"`
	ActiveCount      int64          `json:"active_count"`
	PastDueCount     int64          `json:"past_due_count"`
	CanceledCount    int64          `json:"canceled_count"`
	ExpiredCount     int64          `json:"expired_count"`
	ExpiredTrials    int64          `json:"expired_trials"`
	TrialsEndingSoon int64          `json:"trials_ending_soon"`
	ConversionRate   pgtype.Numeric `json:"conversion_rate"`
}

func (q *Queries) GetSubscriptionAnalytics(ctx context.Context) (GetSubscriptionAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionAnalytics)
	var i GetSubscriptionAnalyticsRow
	err := row.Scan(
		&i.TrialCount,
		&i.ActiveCount,
		&i.PastDueCount,
		&i.CanceledCount,
		&i.ExpiredCount,
		&i.ExpiredTrials,
		&i.TrialsEndingSoon,
		&i.ConversionRate,
	)
	return i, err
}

const getSubscriptionPlanByID = `-- name: GetSubscriptionPlanByID :one
SELECT id, name, slug, description, price_monthly, price_yearly, features, max_users, is_active, sort_order, metadata, created_at, updated_at FROM subscription_plans 
WHERE id = $1
`

func (q *Queries) GetSubscriptionPlanByID(ctx context.Context, id pgtype.UUID) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPlanByID, id)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.Features,
		&i.MaxUsers,
		&i.IsActive,
		&i.SortOrder,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionPlanBySlug = `-- name: GetSubscriptionPlanBySlug :one
SELECT id, name, slug, description, price_monthly, price_yearly, features, max_users, is_active, sort_order, metadata, created_at, updated_at FROM subscription_plans 
WHERE slug = $1 AND is_active = true
`

func (q *Queries) GetSubscriptionPlanBySlug(ctx context.Context, slug string) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPlanBySlug, slug)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.Features,
		&i.MaxUsers,
		&i.IsActive,
		&i.SortOrder,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrialsEndingSoon = `-- name: GetTrialsEndingSoon :many
SELECT 
    o.id,
    o.name,
    o.trial_end_date,
    EXTRACT(DAYS FROM o.trial_end_date - CURRENT_TIMESTAMP)::INTEGER as days_remaining
FROM organizations o
WHERE o.subscription_status = 'trial'
  AND o.trial_end_date BETWEEN CURRENT_TIMESTAMP AND CURRENT_TIMESTAMP + INTERVAL '$1 days'
ORDER BY o.trial_end_date ASC
`

type GetTrialsEndingSoonRow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	TrialEndDate  pgtype.Timestamptz `json:"trial_end_date"`
	DaysRemaining int32              `json:"days_remaining"`
}

func (q *Queries) GetTrialsEndingSoon(ctx context.Context) ([]GetTrialsEndingSoonRow, error) {
	rows, err := q.db.Query(ctx, getTrialsEndingSoon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTrialsEndingSoonRow{}
	for rows.Next() {
		var i GetTrialsEndingSoonRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TrialEndDate,
			&i.DaysRemaining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrganizationGracePeriod = `-- name: SetOrganizationGracePeriod :exec
UPDATE organizations SET
    grace_period_ends_at = CURRENT_TIMESTAMP + INTERVAL '$2 days',
    subscription_status = 'past_due',
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SetOrganizationGracePeriod(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setOrganizationGracePeriod, id)
	return err
}

const startOrganizationTrial = `-- name: StartOrganizationTrial :exec
SELECT start_organization_trial($1::VARCHAR)
`

func (q *Queries) StartOrganizationTrial(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, startOrganizationTrial, dollar_1)
	return err
}

const updateFeatureFlag = `-- name: UpdateFeatureFlag :one
UPDATE subscription_feature_requirements SET
    description = $2,
    plan_requirements = $3,
    is_trial_allowed = $4,
    is_enterprise_only = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE name = $1
RETURNING name, description, plan_requirements, is_trial_allowed, is_enterprise_only, created_at, updated_at
`

func (q *Queries) UpdateFeatureFlag(ctx context.Context, name string, description *string, planRequirements []byte, isTrialAllowed bool, isEnterpriseOnly bool) (SubscriptionFeatureRequirement, error) {
	row := q.db.QueryRow(ctx, updateFeatureFlag,
		name,
		description,
		planRequirements,
		isTrialAllowed,
		isEnterpriseOnly,
	)
	var i SubscriptionFeatureRequirement
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.PlanRequirements,
		&i.IsTrialAllowed,
		&i.IsEnterpriseOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationPlan = `-- name: UpdateOrganizationPlan :exec
UPDATE organizations SET
    current_plan_id = $2,
    subscription_status = $3,
    max_users_allowed = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateOrganizationPlan(ctx context.Context, iD string, currentPlanID pgtype.UUID, subscriptionStatus string, maxUsersAllowed *int32) error {
	_, err := q.db.Exec(ctx, updateOrganizationPlan,
		iD,
		currentPlanID,
		subscriptionStatus,
		maxUsersAllowed,
	)
	return err
}

const updateOrganizationSubscription = `-- name: UpdateOrganizationSubscription :one
UPDATE organization_subscriptions SET
    plan_id = $2,
    stripe_subscription_id = $3,
    status = $4,
    current_period_start = $5,
    current_period_end = $6,
    cancel_at_period_end = $7,
    payment_failed_count = $8,
    last_payment_failed_at = $9,
    updated_at = CURRENT_TIMESTAMP
WHERE organization_id = $1
RETURNING id, organization_id, plan_id, stripe_subscription_id, status, current_period_start, current_period_end, cancel_at_period_end, payment_failed_count, last_payment_failed_at, created_at, updated_at
`

type UpdateOrganizationSubscriptionParams struct {
	OrganizationID       string             `json:"organization_id"`
	PlanID               pgtype.UUID        `json:"plan_id"`
	StripeSubscriptionID *string            `json:"stripe_subscription_id"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CancelAtPeriodEnd    *bool              `json:"cancel_at_period_end"`
	PaymentFailedCount   *int32             `json:"payment_failed_count"`
	LastPaymentFailedAt  pgtype.Timestamptz `json:"last_payment_failed_at"`
}

func (q *Queries) UpdateOrganizationSubscription(ctx context.Context, arg UpdateOrganizationSubscriptionParams) (OrganizationSubscription, error) {
	row := q.db.QueryRow(ctx, updateOrganizationSubscription,
		arg.OrganizationID,
		arg.PlanID,
		arg.StripeSubscriptionID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
		arg.PaymentFailedCount,
		arg.LastPaymentFailedAt,
	)
	var i OrganizationSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.PaymentFailedCount,
		&i.LastPaymentFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationSubscriptionStatus = `-- name: UpdateOrganizationSubscriptionStatus :exec
UPDATE organizations SET
    subscription_status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateOrganizationSubscriptionStatus(ctx context.Context, iD string, subscriptionStatus string) error {
	_, err := q.db.Exec(ctx, updateOrganizationSubscriptionStatus, iD, subscriptionStatus)
	return err
}

const updateSubscriptionPlan = `-- name: UpdateSubscriptionPlan :one
UPDATE subscription_plans SET
    name = $2,
    description = $3,
    price_monthly = $4,
    price_yearly = $5,
    features = $6,
    max_users = $7,
    is_active = $8,
    sort_order = $9,
    metadata = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, slug, description, price_monthly, price_yearly, features, max_users, is_active, sort_order, metadata, created_at, updated_at
`

type UpdateSubscriptionPlanParams struct {
	ID           pgtype.UUID    `json:"id"`
	Name         string         `json:"name"`
	Description  *string        `json:"description"`
	PriceMonthly pgtype.Numeric `json:"price_monthly"`
	PriceYearly  pgtype.Numeric `json:"price_yearly"`
	Features     []byte         `json:"features"`
	MaxUsers     *int32         `json:"max_users"`
	IsActive     *bool          `json:"is_active"`
	SortOrder    *int32         `json:"sort_order"`
	Metadata     []byte         `json:"metadata"`
}

func (q *Queries) UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionPlan,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceMonthly,
		arg.PriceYearly,
		arg.Features,
		arg.MaxUsers,
		arg.IsActive,
		arg.SortOrder,
		arg.Metadata,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.Features,
		&i.MaxUsers,
		&i.IsActive,
		&i.SortOrder,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE organization_subscriptions SET
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE organization_id = $1
`

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, organizationID string, status string) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, organizationID, status)
	return err
}
