// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_resets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (
    user_id, token, expires_at
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, token, expires_at, used_at, created_at
`

func (q *Queries) CreatePasswordReset(ctx context.Context, userID string, token string, expiresAt pgtype.Timestamptz) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, userID, token, expiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResets = `-- name: DeleteExpiredPasswordResets :exec
DELETE FROM password_resets WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredPasswordResets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResets)
	return err
}

const deletePasswordResetsByUserID = `-- name: DeletePasswordResetsByUserID :exec
DELETE FROM password_resets WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deletePasswordResetsByUserID, userID)
	return err
}

const deleteUsedPasswordResets = `-- name: DeleteUsedPasswordResets :exec
DELETE FROM password_resets WHERE used_at IS NOT NULL
`

func (q *Queries) DeleteUsedPasswordResets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteUsedPasswordResets)
	return err
}

const getPasswordResetByToken = `-- name: GetPasswordResetByToken :one
SELECT id, user_id, token, expires_at, used_at, created_at FROM password_resets 
WHERE token = $1 AND used_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetPasswordResetByToken(ctx context.Context, token string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByToken, token)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetAsUsed = `-- name: MarkPasswordResetAsUsed :exec
UPDATE password_resets SET 
    used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkPasswordResetAsUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetAsUsed, id)
	return err
}
