// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_vouchers.sql

package db

import (
	"context"
)

const countPaymentVouchersAll = `-- name: CountPaymentVouchersAll :one

SELECT COUNT(*) FROM payment_vouchers
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status) = UPPER($2))
  AND ($3::text = '' OR vendor_id     = $3)
`

// Payment voucher read queries.
// Three scope variants:
//
//	All         → scope.CanViewAll
//	Procurement → scope.IsProcurement (linked_po != '' filter)
//	Limited     → default (owner + workflow_tasks involvement filter)
func (q *Queries) CountPaymentVouchersAll(ctx context.Context, organizationID string, column2 string, column3 string) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentVouchersAll, organizationID, column2, column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentVouchersLimited = `-- name: CountPaymentVouchersLimited :one
SELECT COUNT(*) FROM payment_vouchers pv
WHERE pv.organization_id = $1
  AND ($2::text = '' OR UPPER(pv.status) = UPPER($2))
  AND ($3::text = '' OR pv.vendor_id     = $3)
  AND (
      pv.created_by = $4
      OR pv.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'payment_voucher'
            AND (
                wt.assigned_user_id        = $4
                OR LOWER(wt.assigned_role) = LOWER($5)
                OR wt.assigned_role        = ANY($6::text[])
                OR wt.claimed_by           = $4
            )
      )
  )
`

type CountPaymentVouchersLimitedParams struct {
	OrganizationID string   `json:"organization_id"`
	Column2        string   `json:"column_2"`
	Column3        string   `json:"column_3"`
	CreatedBy      *string  `json:"created_by"`
	Lower          string   `json:"lower"`
	Column6        []string `json:"column_6"`
}

func (q *Queries) CountPaymentVouchersLimited(ctx context.Context, arg CountPaymentVouchersLimitedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentVouchersLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.CreatedBy,
		arg.Lower,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentVouchersProcurement = `-- name: CountPaymentVouchersProcurement :one
SELECT COUNT(*) FROM payment_vouchers pv
WHERE pv.organization_id = $1
  AND pv.linked_po IS NOT NULL
  AND pv.linked_po != ''
  AND ($2::text = '' OR UPPER(pv.status) = UPPER($2))
  AND ($3::text = '' OR pv.vendor_id     = $3)
`

func (q *Queries) CountPaymentVouchersProcurement(ctx context.Context, organizationID string, column2 string, column3 string) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentVouchersProcurement, organizationID, column2, column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPaymentVoucherIDsAll = `-- name: ListPaymentVoucherIDsAll :many
SELECT id FROM payment_vouchers
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status) = UPPER($2))
  AND ($3::text = '' OR vendor_id     = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

func (q *Queries) ListPaymentVoucherIDsAll(ctx context.Context, organizationID string, column2 string, column3 string, limit int32, offset int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listPaymentVoucherIDsAll,
		organizationID,
		column2,
		column3,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentVoucherIDsLimited = `-- name: ListPaymentVoucherIDsLimited :many
SELECT pv.id FROM payment_vouchers pv
WHERE pv.organization_id = $1
  AND ($2::text = '' OR UPPER(pv.status) = UPPER($2))
  AND ($3::text = '' OR pv.vendor_id     = $3)
  AND (
      pv.created_by = $4
      OR pv.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'payment_voucher'
            AND (
                wt.assigned_user_id        = $4
                OR LOWER(wt.assigned_role) = LOWER($5)
                OR wt.assigned_role        = ANY($6::text[])
                OR wt.claimed_by           = $4
            )
      )
  )
ORDER BY pv.created_at DESC
LIMIT $7 OFFSET $8
`

type ListPaymentVoucherIDsLimitedParams struct {
	OrganizationID string   `json:"organization_id"`
	Column2        string   `json:"column_2"`
	Column3        string   `json:"column_3"`
	CreatedBy      *string  `json:"created_by"`
	Lower          string   `json:"lower"`
	Column6        []string `json:"column_6"`
	Limit          int32    `json:"limit"`
	Offset         int32    `json:"offset"`
}

func (q *Queries) ListPaymentVoucherIDsLimited(ctx context.Context, arg ListPaymentVoucherIDsLimitedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPaymentVoucherIDsLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.CreatedBy,
		arg.Lower,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentVoucherIDsProcurement = `-- name: ListPaymentVoucherIDsProcurement :many
SELECT pv.id FROM payment_vouchers pv
WHERE pv.organization_id = $1
  AND pv.linked_po IS NOT NULL
  AND pv.linked_po != ''
  AND ($2::text = '' OR UPPER(pv.status) = UPPER($2))
  AND ($3::text = '' OR pv.vendor_id     = $3)
ORDER BY pv.created_at DESC
LIMIT $4 OFFSET $5
`

func (q *Queries) ListPaymentVoucherIDsProcurement(ctx context.Context, organizationID string, column2 string, column3 string, limit int32, offset int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listPaymentVoucherIDsProcurement,
		organizationID,
		column2,
		column3,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
