// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchase_orders.sql

package db

import (
	"context"
)

const countPurchaseOrdersAll = `-- name: CountPurchaseOrdersAll :one

SELECT COUNT(*) FROM purchase_orders
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status)    = UPPER($2))
  AND ($3::text = '' OR vendor_id        = $3)
`

// Purchase order read queries.
// Both CanViewAll and IsProcurement return all POs (ApplyToQuery passes through for both).
// Only two scope variants needed: All and Limited.
func (q *Queries) CountPurchaseOrdersAll(ctx context.Context, organizationID string, column2 string, column3 string) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseOrdersAll, organizationID, column2, column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPurchaseOrdersLimited = `-- name: CountPurchaseOrdersLimited :one
SELECT COUNT(*) FROM purchase_orders po
WHERE po.organization_id = $1
  AND ($2::text = '' OR UPPER(po.status) = UPPER($2))
  AND ($3::text = '' OR po.vendor_id     = $3)
  AND (
      po.created_by = $4
      OR po.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'purchase_order'
            AND (
                wt.assigned_user_id        = $4
                OR LOWER(wt.assigned_role) = LOWER($5)
                OR wt.assigned_role        = ANY($6::text[])
                OR wt.claimed_by           = $4
            )
      )
  )
`

type CountPurchaseOrdersLimitedParams struct {
	OrganizationID string   `json:"organization_id"`
	Column2        string   `json:"column_2"`
	Column3        string   `json:"column_3"`
	CreatedBy      *string  `json:"created_by"`
	Lower          string   `json:"lower"`
	Column6        []string `json:"column_6"`
}

func (q *Queries) CountPurchaseOrdersLimited(ctx context.Context, arg CountPurchaseOrdersLimitedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseOrdersLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.CreatedBy,
		arg.Lower,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPurchaseOrderIDsAll = `-- name: ListPurchaseOrderIDsAll :many
SELECT id FROM purchase_orders
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status)    = UPPER($2))
  AND ($3::text = '' OR vendor_id        = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

func (q *Queries) ListPurchaseOrderIDsAll(ctx context.Context, organizationID string, column2 string, column3 string, limit int32, offset int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderIDsAll,
		organizationID,
		column2,
		column3,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrderIDsLimited = `-- name: ListPurchaseOrderIDsLimited :many
SELECT po.id FROM purchase_orders po
WHERE po.organization_id = $1
  AND ($2::text = '' OR UPPER(po.status) = UPPER($2))
  AND ($3::text = '' OR po.vendor_id     = $3)
  AND (
      po.created_by = $4
      OR po.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'purchase_order'
            AND (
                wt.assigned_user_id        = $4
                OR LOWER(wt.assigned_role) = LOWER($5)
                OR wt.assigned_role        = ANY($6::text[])
                OR wt.claimed_by           = $4
            )
      )
  )
ORDER BY po.created_at DESC
LIMIT $7 OFFSET $8
`

type ListPurchaseOrderIDsLimitedParams struct {
	OrganizationID string   `json:"organization_id"`
	Column2        string   `json:"column_2"`
	Column3        string   `json:"column_3"`
	CreatedBy      *string  `json:"created_by"`
	Lower          string   `json:"lower"`
	Column6        []string `json:"column_6"`
	Limit          int32    `json:"limit"`
	Offset         int32    `json:"offset"`
}

func (q *Queries) ListPurchaseOrderIDsLimited(ctx context.Context, arg ListPurchaseOrderIDsLimitedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderIDsLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.CreatedBy,
		arg.Lower,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
