// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateUser(ctx context.Context, id string) error
	ActivateWorkflow(ctx context.Context, iD pgtype.UUID, organizationID string) (Workflow, error)
	// User role assignments
	AssignUserRole(ctx context.Context, userID string, organizationID string, roleID pgtype.UUID, assignedBy *string) (UserOrganizationRole, error)
	CleanupExpiredLockouts(ctx context.Context) error
	CountActiveSessions(ctx context.Context) (int64, error)
	CountActiveUsers(ctx context.Context) (int64, error)
	CountActiveWorkflows(ctx context.Context, organizationID string) (int64, error)
	CountCustomRoles(ctx context.Context, organizationID string) (int64, error)
	CountOrganizationRoles(ctx context.Context, organizationID string) (int64, error)
	CountUserActiveSessions(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWorkflows(ctx context.Context, organizationID string) (int64, error)
	CountWorkflowsByDocumentType(ctx context.Context, organizationID string, documentType string) (int64, error)
	CreateAccountLockout(ctx context.Context, userID string, email string, ipAddress *string, reason string, unlocksAt pgtype.Timestamp) (AccountLockout, error)
	CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) (LoginAttempt, error)
	// Enhanced RBAC with custom organization roles
	CreateOrganizationRole(ctx context.Context, arg CreateOrganizationRoleParams) (OrganizationRole, error)
	CreatePasswordReset(ctx context.Context, userID string, token string, expiresAt pgtype.Timestamp) (PasswordReset, error)
	CreateSession(ctx context.Context, userID string, refreshToken string, ipAddress *string, userAgent *string, expiresAt pgtype.Timestamp) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	DeactivateOrganizationRole(ctx context.Context, id pgtype.UUID) error
	DeactivateUser(ctx context.Context, id string) error
	DeactivateWorkflow(ctx context.Context, iD pgtype.UUID, organizationID string) (Workflow, error)
	DeleteExpiredPasswordResets(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteOldLoginAttempts(ctx context.Context, attemptedAt pgtype.Timestamp) error
	DeletePasswordResetsByUserID(ctx context.Context, userID string) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteSessionByRefreshToken(ctx context.Context, refreshToken string) error
	DeleteSessionsByUserID(ctx context.Context, userID string) error
	DeleteUsedPasswordResets(ctx context.Context) error
	DeleteWorkflow(ctx context.Context, iD pgtype.UUID, organizationID string) error
	GetAccountLockoutByEmail(ctx context.Context, email string) (AccountLockout, error)
	GetAccountLockoutHistory(ctx context.Context, userID string, limit int32, offset int32) ([]AccountLockout, error)
	GetActiveAccountLockout(ctx context.Context, userID string) (AccountLockout, error)
	GetDefaultWorkflowByDocumentType(ctx context.Context, organizationID string, documentType string) (Workflow, error)
	GetLoginAttemptsByEmail(ctx context.Context, email string, limit int32, offset int32) ([]LoginAttempt, error)
	GetLoginAttemptsByUser(ctx context.Context, userID *string, limit int32, offset int32) ([]LoginAttempt, error)
	GetOrganizationRoleByID(ctx context.Context, id pgtype.UUID) (OrganizationRole, error)
	GetOrganizationRoleByName(ctx context.Context, organizationID string, name string) (OrganizationRole, error)
	GetPasswordResetByToken(ctx context.Context, token string) (PasswordReset, error)
	GetRecentFailedAttempts(ctx context.Context, email string, attemptedAt pgtype.Timestamp) (int64, error)
	GetRecentFailedAttemptsByIP(ctx context.Context, ipAddress *string, attemptedAt pgtype.Timestamp) (int64, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error)
	GetSessionsByUserID(ctx context.Context, userID string) ([]Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Enhanced user queries with security features
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserRoleAssignments(ctx context.Context, userID string, organizationID string) ([]GetUserRoleAssignmentsRow, error)
	GetUserRoles(ctx context.Context, userID string, organizationID string) ([]OrganizationRole, error)
	GetWorkflowByID(ctx context.Context, iD pgtype.UUID, organizationID string) (Workflow, error)
	ListActiveWorkflows(ctx context.Context, organizationID string, limit int32, offset int32) ([]Workflow, error)
	ListActiveWorkflowsByDocumentType(ctx context.Context, organizationID string, documentType string, limit int32, offset int32) ([]Workflow, error)
	ListCustomRoles(ctx context.Context, organizationID string, limit int32, offset int32) ([]OrganizationRole, error)
	ListOrganizationRoles(ctx context.Context, organizationID string, limit int32, offset int32) ([]OrganizationRole, error)
	ListSystemRoles(ctx context.Context, organizationID string) ([]OrganizationRole, error)
	ListUsers(ctx context.Context, limit int32, offset int32) ([]User, error)
	ListUsersByOrganization(ctx context.Context, organizationID string, limit int32, offset int32) ([]User, error)
	ListUsersWithRole(ctx context.Context, organizationID string, roleID pgtype.UUID, limit int32, offset int32) ([]ListUsersWithRoleRow, error)
	ListWorkflows(ctx context.Context, organizationID string, limit int32, offset int32) ([]Workflow, error)
	ListWorkflowsByDocumentType(ctx context.Context, organizationID string, documentType string, limit int32, offset int32) ([]Workflow, error)
	MarkPasswordResetAsUsed(ctx context.Context, id pgtype.UUID) error
	RemoveAllUserRoles(ctx context.Context, userID string, organizationID string) error
	RemoveUserRole(ctx context.Context, userID string, organizationID string, roleID pgtype.UUID) error
	UnlockAccount(ctx context.Context, userID string) error
	UnlockAccountByEmail(ctx context.Context, email string) error
	UpdateOrganizationRole(ctx context.Context, iD pgtype.UUID, name string, description *string, permissions []byte) (OrganizationRole, error)
	UpdateSessionRefreshToken(ctx context.Context, iD pgtype.UUID, refreshToken string, expiresAt pgtype.Timestamp, refreshToken_2 string) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id string) error
	UpdateUserPassword(ctx context.Context, iD string, password string) error
	UpdateWorkflow(ctx context.Context, iD pgtype.UUID, organizationID string, name string, description *string, stages []byte) (Workflow, error)
}

var _ Querier = (*Queries)(nil)
