// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateUser(ctx context.Context, id string) error
	ActivateWorkflow(ctx context.Context, iD pgtype.UUID, organizationID string) (Workflow, error)
	// User role assignments
	AssignUserRole(ctx context.Context, userID string, organizationID string, roleID pgtype.UUID, assignedBy *string) (UserOrganizationRole, error)
	CheckOrganizationFeatureAccess(ctx context.Context, orgID string, featureName string) (bool, error)
	CheckOrganizationUserLimit(ctx context.Context, id string) (bool, error)
	CleanupExpiredLockouts(ctx context.Context) error
	CountActiveSessions(ctx context.Context) (int64, error)
	CountActiveUsers(ctx context.Context) (int64, error)
	CountActiveWorkflows(ctx context.Context, organizationID string) (int64, error)
	CountAuditEvents(ctx context.Context, organizationID string, documentType string, documentID string) (int64, error)
	// Audit log queries
	// Uses empty-string = skip-filter pattern to avoid nullable params.
	// All queries return the full row (no preloads needed for audit logs).
	CountAuditLogs(ctx context.Context, organizationID string, column2 string, column3 string, column4 string) (int64, error)
	CountCustomRoles(ctx context.Context, organizationID *string) (int64, error)
	CountDocumentAuditLogs(ctx context.Context, organizationID string, documentID string) (int64, error)
	// Goods received note read queries.
	// Both CanViewAll and IsProcurement use the unfiltered path (ApplyToQuery passes through).
	// Limited adds owner (created_by OR received_by) + workflow_tasks involvement.
	CountGRNsAll(ctx context.Context, arg CountGRNsAllParams) (int64, error)
	CountGRNsLimited(ctx context.Context, arg CountGRNsLimitedParams) (int64, error)
	CountOrganizationRoles(ctx context.Context, organizationID *string) (int64, error)
	// Payment voucher read queries.
	// Three scope variants:
	//   All         → scope.CanViewAll
	//   Procurement → scope.IsProcurement (linked_po != '' filter)
	//   Limited     → default (owner + workflow_tasks involvement filter)
	CountPaymentVouchersAll(ctx context.Context, arg CountPaymentVouchersAllParams) (int64, error)
	CountPaymentVouchersLimited(ctx context.Context, arg CountPaymentVouchersLimitedParams) (int64, error)
	CountPaymentVouchersProcurement(ctx context.Context, arg CountPaymentVouchersProcurementParams) (int64, error)
	// Purchase order read queries.
	// Both CanViewAll and IsProcurement return all POs (ApplyToQuery passes through for both).
	// Only two scope variants needed: All and Limited.
	CountPurchaseOrdersAll(ctx context.Context, arg CountPurchaseOrdersAllParams) (int64, error)
	CountPurchaseOrdersLimited(ctx context.Context, arg CountPurchaseOrdersLimitedParams) (int64, error)
	// Requisition read queries.
	// List queries return only `id`; the handler fetches full data via GORM with Preload
	// to avoid complex pgtype↔model conversions. This keeps mappers unchanged.
	// Three scope variants per list/count pair:
	//   All         → scope.CanViewAll
	//   Procurement → scope.IsProcurement (workflow_assignments subquery filter)
	//   Limited     → default (owner + workflow_tasks involvement filter)
	CountRequisitionsAll(ctx context.Context, arg CountRequisitionsAllParams) (int64, error)
	CountRequisitionsLimited(ctx context.Context, arg CountRequisitionsLimitedParams) (int64, error)
	CountRequisitionsProcurement(ctx context.Context, arg CountRequisitionsProcurementParams) (int64, error)
	CountUserActiveSessions(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWorkflows(ctx context.Context, organizationID string) (int64, error)
	CountWorkflowsByDocumentType(ctx context.Context, organizationID string, documentType string) (int64, error)
	CreateAccountLockout(ctx context.Context, userID string, email string, ipAddress *string, reason string, unlocksAt pgtype.Timestamptz) (AccountLockout, error)
	CreateFeatureFlag(ctx context.Context, name string, description *string, planRequirements []byte, isTrialAllowed bool, isEnterpriseOnly bool) (SubscriptionFeatureRequirement, error)
	CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) (LoginAttempt, error)
	// Enhanced RBAC with global system roles + org custom roles
	CreateOrganizationRole(ctx context.Context, arg CreateOrganizationRoleParams) (OrganizationRole, error)
	CreateOrganizationSubscription(ctx context.Context, arg CreateOrganizationSubscriptionParams) (OrganizationSubscription, error)
	CreatePasswordReset(ctx context.Context, userID string, token string, expiresAt pgtype.Timestamptz) (PasswordReset, error)
	CreateSession(ctx context.Context, userID string, refreshToken string, ipAddress *string, userAgent *string, expiresAt pgtype.Timestamptz) (Session, error)
	// ============================================================================
	// AUDIT LOG QUERIES
	// ============================================================================
	CreateSubscriptionAuditLog(ctx context.Context, arg CreateSubscriptionAuditLogParams) (SubscriptionAuditLog, error)
	CreateSubscriptionPlan(ctx context.Context, arg CreateSubscriptionPlanParams) (SubscriptionPlan, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	DeactivateOrganizationRole(ctx context.Context, id pgtype.UUID) error
	DeactivateUser(ctx context.Context, id string) error
	DeactivateWorkflow(ctx context.Context, iD pgtype.UUID, organizationID string) (Workflow, error)
	DeleteExpiredPasswordResets(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteOldLoginAttempts(ctx context.Context, attemptedAt pgtype.Timestamptz) error
	DeletePasswordResetsByUserID(ctx context.Context, userID string) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteSessionByRefreshToken(ctx context.Context, refreshToken string) error
	DeleteSessionsByUserID(ctx context.Context, userID string) error
	DeleteSubscriptionPlan(ctx context.Context, id pgtype.UUID) error
	DeleteUsedPasswordResets(ctx context.Context) error
	DeleteWorkflow(ctx context.Context, iD pgtype.UUID, organizationID string) error
	ExtendOrganizationTrial(ctx context.Context, column1 string, column2 int32, column3 string) error
	GetAccountLockoutByEmail(ctx context.Context, email string) (AccountLockout, error)
	GetAccountLockoutHistory(ctx context.Context, userID string, limit int32, offset int32) ([]AccountLockout, error)
	GetActiveAccountLockout(ctx context.Context, userID string) (AccountLockout, error)
	// ============================================================================
	// FEATURE FLAGS QUERIES
	// ============================================================================
	GetAllFeatureFlags(ctx context.Context) ([]FeatureFlag, error)
	// ============================================================================
	// ADMIN QUERIES
	// ============================================================================
	GetAllOrganizationsWithSubscriptionStatus(ctx context.Context, limit int32, offset int32) ([]GetAllOrganizationsWithSubscriptionStatusRow, error)
	// ============================================================================
	// SUBSCRIPTION PLANS QUERIES
	// ============================================================================
	GetAllSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error)
	GetDefaultWorkflowByDocumentType(ctx context.Context, organizationID string, documentType string) (Workflow, error)
	GetFeatureFlagByName(ctx context.Context, name string) (FeatureFlag, error)
	GetFeatureFlagsForPlan(ctx context.Context, planRequirements []byte, column2 interface{}) ([]SubscriptionFeatureRequirement, error)
	// Batch enrichment queries for document cross-linking.
	// These replace the existing config.DB.Raw(DISTINCT ON...) calls in the list handlers.
	// pgx/v5 encodes []string natively for the ANY($n::text[]) array parameter.
	GetLinkedPOsForRequisitions(ctx context.Context, column1 []string, organizationID string) ([]GetLinkedPOsForRequisitionsRow, error)
	GetLinkedPVsForPurchaseOrders(ctx context.Context, column1 []string, organizationID string) ([]GetLinkedPVsForPurchaseOrdersRow, error)
	GetLoginAttemptsByEmail(ctx context.Context, email string, limit int32, offset int32) ([]LoginAttempt, error)
	GetLoginAttemptsByUser(ctx context.Context, userID *string, limit int32, offset int32) ([]LoginAttempt, error)
	GetOrganizationAuditLogs(ctx context.Context, organizationID string, limit int32, offset int32) ([]GetOrganizationAuditLogsRow, error)
	// ============================================================================
	// PLAN LIMITS AND ANALYTICS QUERIES
	// ============================================================================
	GetOrganizationPlanLimits(ctx context.Context, id string) (GetOrganizationPlanLimitsRow, error)
	GetOrganizationRoleByID(ctx context.Context, id pgtype.UUID) (OrganizationRole, error)
	GetOrganizationRoleByName(ctx context.Context, organizationID *string, name string) (OrganizationRole, error)
	GetOrganizationSubscription(ctx context.Context, organizationID string) (OrganizationSubscription, error)
	// ============================================================================
	// ORGANIZATION SUBSCRIPTION QUERIES
	// ============================================================================
	GetOrganizationSubscriptionDetails(ctx context.Context, organizationID string) (OrganizationSubscriptionDetail, error)
	// ============================================================================
	// TRIAL MANAGEMENT QUERIES
	// ============================================================================
	GetOrganizationTrialStatus(ctx context.Context, id string) (GetOrganizationTrialStatusRow, error)
	GetPasswordResetByToken(ctx context.Context, token string) (PasswordReset, error)
	GetPlanDistribution(ctx context.Context) ([]GetPlanDistributionRow, error)
	GetRecentAuditLogs(ctx context.Context, limit int32, offset int32) ([]GetRecentAuditLogsRow, error)
	GetRecentFailedAttempts(ctx context.Context, email string, attemptedAt pgtype.Timestamptz) (int64, error)
	GetRecentFailedAttemptsByIP(ctx context.Context, ipAddress *string, attemptedAt pgtype.Timestamptz) (int64, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error)
	GetSessionsByUserID(ctx context.Context, userID string) ([]Session, error)
	GetSubscriptionAnalytics(ctx context.Context) (GetSubscriptionAnalyticsRow, error)
	GetSubscriptionPlanByID(ctx context.Context, id pgtype.UUID) (SubscriptionPlan, error)
	GetSubscriptionPlanBySlug(ctx context.Context, slug string) (SubscriptionPlan, error)
	GetTrialsEndingSoon(ctx context.Context) ([]GetTrialsEndingSoonRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Enhanced user queries with security features
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserRoleAssignments(ctx context.Context, userID string, organizationID string) ([]GetUserRoleAssignmentsRow, error)
	GetUserRoles(ctx context.Context, userID string, organizationID string) ([]OrganizationRole, error)
	GetWorkflowByID(ctx context.Context, iD pgtype.UUID, organizationID string) (Workflow, error)
	ListActiveWorkflows(ctx context.Context, organizationID string, limit int32, offset int32) ([]Workflow, error)
	ListActiveWorkflowsByDocumentType(ctx context.Context, organizationID string, documentType string, limit int32, offset int32) ([]Workflow, error)
	ListAuditEvents(ctx context.Context, organizationID string, documentType string, documentID string, limit int32, offset int32) ([]ListAuditEventsRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListCustomRoles(ctx context.Context, organizationID *string, limit int32, offset int32) ([]OrganizationRole, error)
	ListDocumentAuditLogs(ctx context.Context, organizationID string, documentID string, limit int32, offset int32) ([]ListDocumentAuditLogsRow, error)
	ListGRNIDsAll(ctx context.Context, arg ListGRNIDsAllParams) ([]string, error)
	ListGRNIDsLimited(ctx context.Context, arg ListGRNIDsLimitedParams) ([]string, error)
	ListOrganizationRoles(ctx context.Context, organizationID *string, limit int32, offset int32) ([]OrganizationRole, error)
	ListPaymentVoucherIDsAll(ctx context.Context, arg ListPaymentVoucherIDsAllParams) ([]string, error)
	ListPaymentVoucherIDsLimited(ctx context.Context, arg ListPaymentVoucherIDsLimitedParams) ([]string, error)
	ListPaymentVoucherIDsProcurement(ctx context.Context, arg ListPaymentVoucherIDsProcurementParams) ([]string, error)
	ListPurchaseOrderIDsAll(ctx context.Context, arg ListPurchaseOrderIDsAllParams) ([]string, error)
	ListPurchaseOrderIDsLimited(ctx context.Context, arg ListPurchaseOrderIDsLimitedParams) ([]string, error)
	ListRequisitionIDsAll(ctx context.Context, arg ListRequisitionIDsAllParams) ([]string, error)
	ListRequisitionIDsLimited(ctx context.Context, arg ListRequisitionIDsLimitedParams) ([]string, error)
	ListRequisitionIDsProcurement(ctx context.Context, arg ListRequisitionIDsProcurementParams) ([]string, error)
	ListSystemRoles(ctx context.Context) ([]OrganizationRole, error)
	ListUsers(ctx context.Context, limit int32, offset int32) ([]User, error)
	ListUsersByOrganization(ctx context.Context, organizationID string, limit int32, offset int32) ([]User, error)
	ListUsersWithRole(ctx context.Context, organizationID string, roleID pgtype.UUID, limit int32, offset int32) ([]ListUsersWithRoleRow, error)
	ListWorkflows(ctx context.Context, organizationID string, limit int32, offset int32) ([]Workflow, error)
	ListWorkflowsByDocumentType(ctx context.Context, organizationID string, documentType string, limit int32, offset int32) ([]Workflow, error)
	MarkPasswordResetAsUsed(ctx context.Context, id pgtype.UUID) error
	RemoveAllUserRoles(ctx context.Context, userID string, organizationID string) error
	RemoveUserRole(ctx context.Context, userID string, organizationID string, roleID pgtype.UUID) error
	SetOrganizationGracePeriod(ctx context.Context, id string) error
	StartOrganizationTrial(ctx context.Context, dollar_1 string) error
	UnlockAccount(ctx context.Context, userID string) error
	UnlockAccountByEmail(ctx context.Context, email string) error
	UpdateFeatureFlag(ctx context.Context, name string, description *string, planRequirements []byte, isTrialAllowed bool, isEnterpriseOnly bool) (SubscriptionFeatureRequirement, error)
	UpdateOrganizationPlan(ctx context.Context, iD string, currentPlanID pgtype.UUID, subscriptionStatus string, maxUsersAllowed *int32) error
	UpdateOrganizationRole(ctx context.Context, iD pgtype.UUID, name string, description *string, permissions []byte) (OrganizationRole, error)
	UpdateOrganizationSubscription(ctx context.Context, arg UpdateOrganizationSubscriptionParams) (OrganizationSubscription, error)
	UpdateOrganizationSubscriptionStatus(ctx context.Context, iD string, subscriptionStatus string) error
	UpdateSessionRefreshToken(ctx context.Context, iD pgtype.UUID, refreshToken string, expiresAt pgtype.Timestamptz, refreshToken_2 string) (int64, error)
	UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) (SubscriptionPlan, error)
	UpdateSubscriptionStatus(ctx context.Context, organizationID string, status string) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id string) error
	UpdateUserPassword(ctx context.Context, iD string, password string) error
	UpdateWorkflow(ctx context.Context, iD pgtype.UUID, organizationID string, name string, description *string, stages []byte) (Workflow, error)
}

var _ Querier = (*Queries)(nil)
