// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requisitions.sql

package db

import (
	"context"
)

const countRequisitionsAll = `-- name: CountRequisitionsAll :one

SELECT COUNT(*) FROM requisitions
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status)     = UPPER($2))
  AND ($3::text = '' OR department        = $3)
  AND ($4::text = '' OR priority          = $4)
  AND (NOT $5::bool OR routing_type != 'direct_payment')
`

type CountRequisitionsAllParams struct {
	OrganizationID    string `json:"organization_id"`
	Column2           string `json:"column_2"`
	Column3           string `json:"column_3"`
	Column4           string `json:"column_4"`
	HideDirectPayment bool   `json:"hide_direct_payment"`
}

// Requisition read queries.
// List queries return only `id`; the handler fetches full data via GORM with Preload
// to avoid complex pgtype↔model conversions. This keeps mappers unchanged.
// Three scope variants per list/count pair:
//
//	All         → scope.CanViewAll
//	Procurement → scope.IsProcurement (workflow_assignments subquery filter)
//	Limited     → default (owner + workflow_tasks involvement filter)
func (q *Queries) CountRequisitionsAll(ctx context.Context, arg CountRequisitionsAllParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequisitionsAll,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.HideDirectPayment,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequisitionsLimited = `-- name: CountRequisitionsLimited :one
SELECT COUNT(*) FROM requisitions r
WHERE r.organization_id = $1
  AND ($2::text = '' OR UPPER(r.status)     = UPPER($2))
  AND ($3::text = '' OR r.department        = $3)
  AND ($4::text = '' OR r.priority          = $4)
  AND (
      r.requester_id = $5
      OR r.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'requisition'
            AND (
                wt.assigned_user_id        = $5
                OR LOWER(wt.assigned_role) = LOWER($6)
                OR wt.assigned_role        = ANY($7::text[])
                OR wt.claimed_by           = $5
            )
      )
  )
`

type CountRequisitionsLimitedParams struct {
	OrganizationID string   `json:"organization_id"`
	Column2        string   `json:"column_2"`
	Column3        string   `json:"column_3"`
	Column4        string   `json:"column_4"`
	RequesterID    string   `json:"requester_id"`
	Lower          string   `json:"lower"`
	Column7        []string `json:"column_7"`
}

func (q *Queries) CountRequisitionsLimited(ctx context.Context, arg CountRequisitionsLimitedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequisitionsLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.RequesterID,
		arg.Lower,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequisitionsProcurement = `-- name: CountRequisitionsProcurement :one
SELECT COUNT(*) FROM requisitions r
WHERE r.organization_id = $1
  AND ($2::text = '' OR UPPER(r.status)   = UPPER($2))
  AND ($3::text = '' OR r.department      = $3)
  AND ($4::text = '' OR r.priority        = $4)
  AND (NOT $5::bool OR r.routing_type != 'direct_payment')
  AND r.id IN (
      SELECT wa.entity_id
      FROM workflow_assignments wa
      JOIN workflows w ON w.id = wa.workflow_id
      WHERE wa.entity_type     = 'requisition'
        AND wa.organization_id = $1
        AND (
            w.conditions->>'routingType' IS NULL OR
            w.conditions->>'routingType' = ''   OR
            w.conditions->>'routingType' = 'procurement'
        )
  )
`

type CountRequisitionsProcurementParams struct {
	OrganizationID    string `json:"organization_id"`
	Column2           string `json:"column_2"`
	Column3           string `json:"column_3"`
	Column4           string `json:"column_4"`
	HideDirectPayment bool   `json:"hide_direct_payment"`
}

func (q *Queries) CountRequisitionsProcurement(ctx context.Context, arg CountRequisitionsProcurementParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequisitionsProcurement,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.HideDirectPayment,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRequisitionIDsAll = `-- name: ListRequisitionIDsAll :many
SELECT id FROM requisitions
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status)     = UPPER($2))
  AND ($3::text = '' OR department        = $3)
  AND ($4::text = '' OR priority          = $4)
  AND (NOT $5::bool OR routing_type != 'direct_payment')
ORDER BY created_at DESC
LIMIT $6 OFFSET $7
`

type ListRequisitionIDsAllParams struct {
	OrganizationID    string `json:"organization_id"`
	Column2           string `json:"column_2"`
	Column3           string `json:"column_3"`
	Column4           string `json:"column_4"`
	HideDirectPayment bool   `json:"hide_direct_payment"`
	Limit             int32  `json:"limit"`
	Offset            int32  `json:"offset"`
}

func (q *Queries) ListRequisitionIDsAll(ctx context.Context, arg ListRequisitionIDsAllParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRequisitionIDsAll,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.HideDirectPayment,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequisitionIDsLimited = `-- name: ListRequisitionIDsLimited :many
SELECT r.id FROM requisitions r
WHERE r.organization_id = $1
  AND ($2::text = '' OR UPPER(r.status)     = UPPER($2))
  AND ($3::text = '' OR r.department        = $3)
  AND ($4::text = '' OR r.priority          = $4)
  AND (
      r.requester_id = $5
      OR r.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'requisition'
            AND (
                wt.assigned_user_id        = $5
                OR LOWER(wt.assigned_role) = LOWER($6)
                OR wt.assigned_role        = ANY($7::text[])
                OR wt.claimed_by           = $5
            )
      )
  )
ORDER BY r.created_at DESC
LIMIT $8 OFFSET $9
`

type ListRequisitionIDsLimitedParams struct {
	OrganizationID string   `json:"organization_id"`
	Column2        string   `json:"column_2"`
	Column3        string   `json:"column_3"`
	Column4        string   `json:"column_4"`
	RequesterID    string   `json:"requester_id"`
	Lower          string   `json:"lower"`
	Column7        []string `json:"column_7"`
	Limit          int32    `json:"limit"`
	Offset         int32    `json:"offset"`
}

func (q *Queries) ListRequisitionIDsLimited(ctx context.Context, arg ListRequisitionIDsLimitedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRequisitionIDsLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.RequesterID,
		arg.Lower,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequisitionIDsProcurement = `-- name: ListRequisitionIDsProcurement :many
SELECT r.id FROM requisitions r
WHERE r.organization_id = $1
  AND ($2::text = '' OR UPPER(r.status)   = UPPER($2))
  AND ($3::text = '' OR r.department      = $3)
  AND ($4::text = '' OR r.priority        = $4)
  AND (NOT $5::bool OR r.routing_type != 'direct_payment')
  AND r.id IN (
      SELECT wa.entity_id
      FROM workflow_assignments wa
      JOIN workflows w ON w.id = wa.workflow_id
      WHERE wa.entity_type     = 'requisition'
        AND wa.organization_id = $1
        AND (
            w.conditions->>'routingType' IS NULL OR
            w.conditions->>'routingType' = ''   OR
            w.conditions->>'routingType' = 'procurement'
        )
  )
ORDER BY r.created_at DESC
LIMIT $6 OFFSET $7
`

type ListRequisitionIDsProcurementParams struct {
	OrganizationID    string `json:"organization_id"`
	Column2           string `json:"column_2"`
	Column3           string `json:"column_3"`
	Column4           string `json:"column_4"`
	HideDirectPayment bool   `json:"hide_direct_payment"`
	Limit             int32  `json:"limit"`
	Offset            int32  `json:"offset"`
}

func (q *Queries) ListRequisitionIDsProcurement(ctx context.Context, arg ListRequisitionIDsProcurementParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRequisitionIDsProcurement,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.HideDirectPayment,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
