// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateWorkflow = `-- name: ActivateWorkflow :one
UPDATE workflows
SET is_active = true,
    updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at
`

func (q *Queries) ActivateWorkflow(ctx context.Context, iD pgtype.UUID, organizationID string) (Workflow, error) {
	row := q.db.QueryRow(ctx, activateWorkflow, iD, organizationID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.EntityType,
		&i.Version,
		&i.Stages,
		&i.Conditions,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveWorkflows = `-- name: CountActiveWorkflows :one
SELECT COUNT(*) FROM workflows
WHERE organization_id = $1 AND is_active = true
`

func (q *Queries) CountActiveWorkflows(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWorkflows, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkflows = `-- name: CountWorkflows :one
SELECT COUNT(*) FROM workflows
WHERE organization_id = $1
`

func (q *Queries) CountWorkflows(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflows, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkflowsByDocumentType = `-- name: CountWorkflowsByDocumentType :one
SELECT COUNT(*) FROM workflows
WHERE organization_id = $1 AND document_type = $2
`

func (q *Queries) CountWorkflowsByDocumentType(ctx context.Context, organizationID string, documentType string) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowsByDocumentType, organizationID, documentType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (
    id,
    organization_id,
    name,
    description,
    document_type,
    stages,
    is_active,
    created_by,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
)
RETURNING id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at
`

type CreateWorkflowParams struct {
	OrganizationID string  `json:"organization_id"`
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	DocumentType   string  `json:"document_type"`
	Stages         []byte  `json:"stages"`
	IsActive       *bool   `json:"is_active"`
	CreatedBy      *string `json:"created_by"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.DocumentType,
		arg.Stages,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.EntityType,
		&i.Version,
		&i.Stages,
		&i.Conditions,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateWorkflow = `-- name: DeactivateWorkflow :one
UPDATE workflows
SET is_active = false,
    updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at
`

func (q *Queries) DeactivateWorkflow(ctx context.Context, iD pgtype.UUID, organizationID string) (Workflow, error) {
	row := q.db.QueryRow(ctx, deactivateWorkflow, iD, organizationID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.EntityType,
		&i.Version,
		&i.Stages,
		&i.Conditions,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows
WHERE id = $1 AND organization_id = $2
`

func (q *Queries) DeleteWorkflow(ctx context.Context, iD pgtype.UUID, organizationID string) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, iD, organizationID)
	return err
}

const getDefaultWorkflowByDocumentType = `-- name: GetDefaultWorkflowByDocumentType :one
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE organization_id = $1 AND document_type = $2 AND is_active = true
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetDefaultWorkflowByDocumentType(ctx context.Context, organizationID string, documentType string) (Workflow, error) {
	row := q.db.QueryRow(ctx, getDefaultWorkflowByDocumentType, organizationID, documentType)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.EntityType,
		&i.Version,
		&i.Stages,
		&i.Conditions,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE id = $1 AND organization_id = $2
`

func (q *Queries) GetWorkflowByID(ctx context.Context, iD pgtype.UUID, organizationID string) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByID, iD, organizationID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.EntityType,
		&i.Version,
		&i.Stages,
		&i.Conditions,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWorkflows = `-- name: ListActiveWorkflows :many
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE organization_id = $1 AND is_active = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListActiveWorkflows(ctx context.Context, organizationID string, limit int32, offset int32) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listActiveWorkflows, organizationID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.EntityType,
			&i.Version,
			&i.Stages,
			&i.Conditions,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWorkflowsByDocumentType = `-- name: ListActiveWorkflowsByDocumentType :many
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE organization_id = $1 AND document_type = $2 AND is_active = true
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListActiveWorkflowsByDocumentType(ctx context.Context, organizationID string, documentType string, limit int32, offset int32) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listActiveWorkflowsByDocumentType,
		organizationID,
		documentType,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.EntityType,
			&i.Version,
			&i.Stages,
			&i.Conditions,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListWorkflows(ctx context.Context, organizationID string, limit int32, offset int32) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, organizationID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.EntityType,
			&i.Version,
			&i.Stages,
			&i.Conditions,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsByDocumentType = `-- name: ListWorkflowsByDocumentType :many
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE organization_id = $1 AND document_type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListWorkflowsByDocumentType(ctx context.Context, organizationID string, documentType string, limit int32, offset int32) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflowsByDocumentType,
		organizationID,
		documentType,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.EntityType,
			&i.Version,
			&i.Stages,
			&i.Conditions,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows
SET name = $3,
    description = $4,
    stages = $5,
    updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at
`

func (q *Queries) UpdateWorkflow(ctx context.Context, iD pgtype.UUID, organizationID string, name string, description *string, stages []byte) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		iD,
		organizationID,
		name,
		description,
		stages,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.EntityType,
		&i.Version,
		&i.Stages,
		&i.Conditions,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
