-- ============================================================================
-- SUPPORT TICKETS SEED DATA
-- Migration: 013_seed_support_tickets
-- Adds demo support tickets for the admin console.
-- ============================================================================

INSERT INTO support_tickets (
    id,
    ticket_number,
    organization_id,
    user_id,
    created_by_admin_id,
    assigned_to_admin_id,
    source,
    category,
    priority,
    status,
    subject,
    description,
    internal_notes,
    external_reference,
    resolution_summary,
    metadata,
    resolved_at,
    closed_at,
    created_at,
    updated_at
)
VALUES
    (
        'ticket-manual-001',
        'TCK-260422-001',
        'org-demo-001',
        'user-requester-001',
        'user-super-admin-001',
        'user-admin-001',
        'manual',
        'access',
        'high',
        'open',
        'Unable to access approval queue',
        'Requester reports the approvals list is not visible in the support console test environment.',
        'Seeded for admin console manual ticket workflow testing.',
        'manual-demo-001',
        '',
        jsonb_build_object(
            'seeded', true,
            'source', 'manual',
            'surface', 'admin-console',
            'issue_type', 'access'
        ),
        NULL,
        NULL,
        CURRENT_TIMESTAMP - INTERVAL '3 days',
        CURRENT_TIMESTAMP - INTERVAL '3 days'
    ),
    (
        'ticket-userapp-001',
        'TCK-260422-002',
        'org-demo-001',
        'user-finance-001',
        'user-super-admin-001',
        'user-admin-001',
        'user_app',
        'workflow',
        'medium',
        'in_progress',
        'Workflow task stuck after submission',
        'A requisition appears to have stalled after submission. Use this to verify workflow triage and reassignment flows.',
        'Seeded to exercise workflow support actions.',
        'user-app-issue-142',
        '',
        jsonb_build_object(
            'seeded', true,
            'source', 'user_app',
            'surface', 'mobile',
            'issue_type', 'stalled_workflow'
        ),
        NULL,
        NULL,
        CURRENT_TIMESTAMP - INTERVAL '2 days',
        CURRENT_TIMESTAMP - INTERVAL '2 days'
    ),
    (
        'ticket-email-001',
        'TCK-260422-003',
        'org-enterprise-001',
        'user-approver-001',
        'user-super-admin-001',
        'user-admin-001',
        'email',
        'billing',
        'urgent',
        'waiting_on_customer',
        'Subscription invoice mismatch for enterprise plan',
        'Customer says the invoice total does not match the contracted plan amount.',
        'Seeded to test email-origin support intake.',
        'support-thread-8871',
        '',
        jsonb_build_object(
            'seeded', true,
            'source', 'email',
            'surface', 'mailbox',
            'issue_type', 'billing_dispute'
        ),
        NULL,
        NULL,
        CURRENT_TIMESTAMP - INTERVAL '5 days',
        CURRENT_TIMESTAMP - INTERVAL '5 days'
    ),
    (
        'ticket-manual-002',
        'TCK-260422-004',
        'org-demo-001',
        'user-requester-001',
        'user-super-admin-001',
        'user-admin-001',
        'manual',
        'bug',
        'low',
        'resolved',
        'Export CSV missing one column',
        'Manual seed ticket for validating resolved ticket filtering and detail views.',
        'Confirmed and closed during dashboard smoke testing.',
        'manual-demo-002',
        'Export mapping corrected and verified against the latest CSV export.',
        jsonb_build_object(
            'seeded', true,
            'source', 'manual',
            'surface', 'admin-console',
            'issue_type', 'export_bug'
        ),
        CURRENT_TIMESTAMP - INTERVAL '1 day',
        CURRENT_TIMESTAMP - INTERVAL '1 day',
        CURRENT_TIMESTAMP - INTERVAL '4 days',
        CURRENT_TIMESTAMP - INTERVAL '1 day'
    )
ON CONFLICT (ticket_number) DO UPDATE SET
    organization_id      = EXCLUDED.organization_id,
    user_id              = EXCLUDED.user_id,
    created_by_admin_id  = EXCLUDED.created_by_admin_id,
    assigned_to_admin_id = EXCLUDED.assigned_to_admin_id,
    source               = EXCLUDED.source,
    category             = EXCLUDED.category,
    priority             = EXCLUDED.priority,
    status               = EXCLUDED.status,
    subject              = EXCLUDED.subject,
    description          = EXCLUDED.description,
    internal_notes       = EXCLUDED.internal_notes,
    external_reference   = EXCLUDED.external_reference,
    resolution_summary   = EXCLUDED.resolution_summary,
    metadata             = EXCLUDED.metadata,
    resolved_at          = EXCLUDED.resolved_at,
    closed_at            = EXCLUDED.closed_at,
    updated_at           = CURRENT_TIMESTAMP;
