-- Add MFA and LDAP flags to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_ldap_user BOOLEAN NOT NULL DEFAULT FALSE;
