// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approval_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApprovalHistoryByTask = `-- name: CountApprovalHistoryByTask :one
SELECT COUNT(*) FROM approval_history
WHERE task_id = $1
`

func (q *Queries) CountApprovalHistoryByTask(ctx context.Context, taskID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovalHistoryByTask, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApprovalHistoryByUser = `-- name: CountApprovalHistoryByUser :one
SELECT COUNT(*) FROM approval_history
WHERE user_id = $1
`

func (q *Queries) CountApprovalHistoryByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovalHistoryByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovalHistoryEntry = `-- name: CreateApprovalHistoryEntry :one
INSERT INTO approval_history (
    task_id,
    user_id,
    action,
    stage,
    comment,
    signature,
    ip_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, task_id, user_id, action, stage, comment, signature, ip_address, created_at
`

type CreateApprovalHistoryEntryParams struct {
	TaskID    pgtype.UUID `json:"task_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Action    string      `json:"action"`
	Stage     int32       `json:"stage"`
	Comment   pgtype.Text `json:"comment"`
	Signature pgtype.Text `json:"signature"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateApprovalHistoryEntry(ctx context.Context, arg CreateApprovalHistoryEntryParams) (ApprovalHistory, error) {
	row := q.db.QueryRow(ctx, createApprovalHistoryEntry,
		arg.TaskID,
		arg.UserID,
		arg.Action,
		arg.Stage,
		arg.Comment,
		arg.Signature,
		arg.IpAddress,
	)
	var i ApprovalHistory
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Action,
		&i.Stage,
		&i.Comment,
		&i.Signature,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const deleteApprovalHistory = `-- name: DeleteApprovalHistory :exec
DELETE FROM approval_history
WHERE id = $1
`

func (q *Queries) DeleteApprovalHistory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApprovalHistory, id)
	return err
}

const getApprovalHistoryByID = `-- name: GetApprovalHistoryByID :one
SELECT id, task_id, user_id, action, stage, comment, signature, ip_address, created_at FROM approval_history
WHERE id = $1
`

func (q *Queries) GetApprovalHistoryByID(ctx context.Context, id pgtype.UUID) (ApprovalHistory, error) {
	row := q.db.QueryRow(ctx, getApprovalHistoryByID, id)
	var i ApprovalHistory
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Action,
		&i.Stage,
		&i.Comment,
		&i.Signature,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestApprovalHistoryByTask = `-- name: GetLatestApprovalHistoryByTask :one
SELECT id, task_id, user_id, action, stage, comment, signature, ip_address, created_at FROM approval_history
WHERE task_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestApprovalHistoryByTask(ctx context.Context, taskID pgtype.UUID) (ApprovalHistory, error) {
	row := q.db.QueryRow(ctx, getLatestApprovalHistoryByTask, taskID)
	var i ApprovalHistory
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Action,
		&i.Stage,
		&i.Comment,
		&i.Signature,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovalHistoryByAction = `-- name: ListApprovalHistoryByAction :many
SELECT id, task_id, user_id, action, stage, comment, signature, ip_address, created_at FROM approval_history
WHERE action = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListApprovalHistoryByActionParams struct {
	Action string `json:"action"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListApprovalHistoryByAction(ctx context.Context, arg ListApprovalHistoryByActionParams) ([]ApprovalHistory, error) {
	rows, err := q.db.Query(ctx, listApprovalHistoryByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalHistory{}
	for rows.Next() {
		var i ApprovalHistory
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Action,
			&i.Stage,
			&i.Comment,
			&i.Signature,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalHistoryByTask = `-- name: ListApprovalHistoryByTask :many
SELECT id, task_id, user_id, action, stage, comment, signature, ip_address, created_at FROM approval_history
WHERE task_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListApprovalHistoryByTask(ctx context.Context, taskID pgtype.UUID) ([]ApprovalHistory, error) {
	rows, err := q.db.Query(ctx, listApprovalHistoryByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalHistory{}
	for rows.Next() {
		var i ApprovalHistory
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Action,
			&i.Stage,
			&i.Comment,
			&i.Signature,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalHistoryByUser = `-- name: ListApprovalHistoryByUser :many
SELECT id, task_id, user_id, action, stage, comment, signature, ip_address, created_at FROM approval_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListApprovalHistoryByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListApprovalHistoryByUser(ctx context.Context, arg ListApprovalHistoryByUserParams) ([]ApprovalHistory, error) {
	rows, err := q.db.Query(ctx, listApprovalHistoryByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalHistory{}
	for rows.Next() {
		var i ApprovalHistory
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Action,
			&i.Stage,
			&i.Comment,
			&i.Signature,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
