// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approval_tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApprovalTasksByAssignee = `-- name: CountApprovalTasksByAssignee :one
SELECT COUNT(*) FROM approval_tasks
WHERE assigned_to = $1
`

func (q *Queries) CountApprovalTasksByAssignee(ctx context.Context, assignedTo pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovalTasksByAssignee, assignedTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApprovalTasksByStatus = `-- name: CountApprovalTasksByStatus :one
SELECT COUNT(*) FROM approval_tasks
WHERE status = $1
`

func (q *Queries) CountApprovalTasksByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovalTasksByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingApprovalTasksByAssignee = `-- name: CountPendingApprovalTasksByAssignee :one
SELECT COUNT(*) FROM approval_tasks
WHERE assigned_to = $1 AND status = 'PENDING'
`

func (q *Queries) CountPendingApprovalTasksByAssignee(ctx context.Context, assignedTo pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingApprovalTasksByAssignee, assignedTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovalTask = `-- name: CreateApprovalTask :one
INSERT INTO approval_tasks (
    document_id,
    assigned_to,
    assigned_by,
    status,
    current_stage,
    total_stages,
    priority,
    due_date,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, document_id, assigned_to, assigned_by, status, current_stage, total_stages, priority, due_date, notes, created_at, updated_at
`

type CreateApprovalTaskParams struct {
	DocumentID   pgtype.UUID      `json:"document_id"`
	AssignedTo   pgtype.UUID      `json:"assigned_to"`
	AssignedBy   pgtype.UUID      `json:"assigned_by"`
	Status       string           `json:"status"`
	CurrentStage int32            `json:"current_stage"`
	TotalStages  int32            `json:"total_stages"`
	Priority     pgtype.Text      `json:"priority"`
	DueDate      pgtype.Timestamp `json:"due_date"`
	Notes        pgtype.Text      `json:"notes"`
}

func (q *Queries) CreateApprovalTask(ctx context.Context, arg CreateApprovalTaskParams) (ApprovalTask, error) {
	row := q.db.QueryRow(ctx, createApprovalTask,
		arg.DocumentID,
		arg.AssignedTo,
		arg.AssignedBy,
		arg.Status,
		arg.CurrentStage,
		arg.TotalStages,
		arg.Priority,
		arg.DueDate,
		arg.Notes,
	)
	var i ApprovalTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.Status,
		&i.CurrentStage,
		&i.TotalStages,
		&i.Priority,
		&i.DueDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApprovalTask = `-- name: DeleteApprovalTask :exec
DELETE FROM approval_tasks
WHERE id = $1
`

func (q *Queries) DeleteApprovalTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApprovalTask, id)
	return err
}

const getApprovalTaskByID = `-- name: GetApprovalTaskByID :one
SELECT id, document_id, assigned_to, assigned_by, status, current_stage, total_stages, priority, due_date, notes, created_at, updated_at FROM approval_tasks
WHERE id = $1
`

func (q *Queries) GetApprovalTaskByID(ctx context.Context, id pgtype.UUID) (ApprovalTask, error) {
	row := q.db.QueryRow(ctx, getApprovalTaskByID, id)
	var i ApprovalTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.Status,
		&i.CurrentStage,
		&i.TotalStages,
		&i.Priority,
		&i.DueDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovalTasksByAssignee = `-- name: ListApprovalTasksByAssignee :many
SELECT id, document_id, assigned_to, assigned_by, status, current_stage, total_stages, priority, due_date, notes, created_at, updated_at FROM approval_tasks
WHERE assigned_to = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListApprovalTasksByAssigneeParams struct {
	AssignedTo pgtype.UUID `json:"assigned_to"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListApprovalTasksByAssignee(ctx context.Context, arg ListApprovalTasksByAssigneeParams) ([]ApprovalTask, error) {
	rows, err := q.db.Query(ctx, listApprovalTasksByAssignee, arg.AssignedTo, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalTask{}
	for rows.Next() {
		var i ApprovalTask
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AssignedTo,
			&i.AssignedBy,
			&i.Status,
			&i.CurrentStage,
			&i.TotalStages,
			&i.Priority,
			&i.DueDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalTasksByAssigneeAndStatus = `-- name: ListApprovalTasksByAssigneeAndStatus :many
SELECT id, document_id, assigned_to, assigned_by, status, current_stage, total_stages, priority, due_date, notes, created_at, updated_at FROM approval_tasks
WHERE assigned_to = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListApprovalTasksByAssigneeAndStatusParams struct {
	AssignedTo pgtype.UUID `json:"assigned_to"`
	Status     string      `json:"status"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListApprovalTasksByAssigneeAndStatus(ctx context.Context, arg ListApprovalTasksByAssigneeAndStatusParams) ([]ApprovalTask, error) {
	rows, err := q.db.Query(ctx, listApprovalTasksByAssigneeAndStatus,
		arg.AssignedTo,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalTask{}
	for rows.Next() {
		var i ApprovalTask
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AssignedTo,
			&i.AssignedBy,
			&i.Status,
			&i.CurrentStage,
			&i.TotalStages,
			&i.Priority,
			&i.DueDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalTasksByDocument = `-- name: ListApprovalTasksByDocument :many
SELECT id, document_id, assigned_to, assigned_by, status, current_stage, total_stages, priority, due_date, notes, created_at, updated_at FROM approval_tasks
WHERE document_id = $1
ORDER BY current_stage ASC, created_at DESC
`

func (q *Queries) ListApprovalTasksByDocument(ctx context.Context, documentID pgtype.UUID) ([]ApprovalTask, error) {
	rows, err := q.db.Query(ctx, listApprovalTasksByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalTask{}
	for rows.Next() {
		var i ApprovalTask
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AssignedTo,
			&i.AssignedBy,
			&i.Status,
			&i.CurrentStage,
			&i.TotalStages,
			&i.Priority,
			&i.DueDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalTasksByStatus = `-- name: ListApprovalTasksByStatus :many
SELECT id, document_id, assigned_to, assigned_by, status, current_stage, total_stages, priority, due_date, notes, created_at, updated_at FROM approval_tasks
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListApprovalTasksByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListApprovalTasksByStatus(ctx context.Context, arg ListApprovalTasksByStatusParams) ([]ApprovalTask, error) {
	rows, err := q.db.Query(ctx, listApprovalTasksByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalTask{}
	for rows.Next() {
		var i ApprovalTask
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AssignedTo,
			&i.AssignedBy,
			&i.Status,
			&i.CurrentStage,
			&i.TotalStages,
			&i.Priority,
			&i.DueDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueApprovalTasks = `-- name: ListOverdueApprovalTasks :many
SELECT id, document_id, assigned_to, assigned_by, status, current_stage, total_stages, priority, due_date, notes, created_at, updated_at FROM approval_tasks
WHERE status = 'PENDING'
  AND due_date < NOW()
ORDER BY due_date ASC
LIMIT $1 OFFSET $2
`

type ListOverdueApprovalTasksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOverdueApprovalTasks(ctx context.Context, arg ListOverdueApprovalTasksParams) ([]ApprovalTask, error) {
	rows, err := q.db.Query(ctx, listOverdueApprovalTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalTask{}
	for rows.Next() {
		var i ApprovalTask
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AssignedTo,
			&i.AssignedBy,
			&i.Status,
			&i.CurrentStage,
			&i.TotalStages,
			&i.Priority,
			&i.DueDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalTasks = `-- name: ListPendingApprovalTasks :many
SELECT id, document_id, assigned_to, assigned_by, status, current_stage, total_stages, priority, due_date, notes, created_at, updated_at FROM approval_tasks
WHERE status = 'PENDING'
ORDER BY priority DESC, created_at ASC
LIMIT $1 OFFSET $2
`

type ListPendingApprovalTasksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPendingApprovalTasks(ctx context.Context, arg ListPendingApprovalTasksParams) ([]ApprovalTask, error) {
	rows, err := q.db.Query(ctx, listPendingApprovalTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalTask{}
	for rows.Next() {
		var i ApprovalTask
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AssignedTo,
			&i.AssignedBy,
			&i.Status,
			&i.CurrentStage,
			&i.TotalStages,
			&i.Priority,
			&i.DueDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignApprovalTask = `-- name: ReassignApprovalTask :one
UPDATE approval_tasks
SET assigned_to = $2,
    assigned_by = $3,
    status = 'REASSIGNED',
    updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, assigned_to, assigned_by, status, current_stage, total_stages, priority, due_date, notes, created_at, updated_at
`

type ReassignApprovalTaskParams struct {
	ID         pgtype.UUID `json:"id"`
	AssignedTo pgtype.UUID `json:"assigned_to"`
	AssignedBy pgtype.UUID `json:"assigned_by"`
}

func (q *Queries) ReassignApprovalTask(ctx context.Context, arg ReassignApprovalTaskParams) (ApprovalTask, error) {
	row := q.db.QueryRow(ctx, reassignApprovalTask, arg.ID, arg.AssignedTo, arg.AssignedBy)
	var i ApprovalTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.Status,
		&i.CurrentStage,
		&i.TotalStages,
		&i.Priority,
		&i.DueDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApprovalTaskNotes = `-- name: UpdateApprovalTaskNotes :one
UPDATE approval_tasks
SET notes = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, assigned_to, assigned_by, status, current_stage, total_stages, priority, due_date, notes, created_at, updated_at
`

type UpdateApprovalTaskNotesParams struct {
	ID    pgtype.UUID `json:"id"`
	Notes pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateApprovalTaskNotes(ctx context.Context, arg UpdateApprovalTaskNotesParams) (ApprovalTask, error) {
	row := q.db.QueryRow(ctx, updateApprovalTaskNotes, arg.ID, arg.Notes)
	var i ApprovalTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.Status,
		&i.CurrentStage,
		&i.TotalStages,
		&i.Priority,
		&i.DueDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApprovalTaskStage = `-- name: UpdateApprovalTaskStage :one
UPDATE approval_tasks
SET current_stage = $2,
    status = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, assigned_to, assigned_by, status, current_stage, total_stages, priority, due_date, notes, created_at, updated_at
`

type UpdateApprovalTaskStageParams struct {
	ID           pgtype.UUID `json:"id"`
	CurrentStage int32       `json:"current_stage"`
	Status       string      `json:"status"`
}

func (q *Queries) UpdateApprovalTaskStage(ctx context.Context, arg UpdateApprovalTaskStageParams) (ApprovalTask, error) {
	row := q.db.QueryRow(ctx, updateApprovalTaskStage, arg.ID, arg.CurrentStage, arg.Status)
	var i ApprovalTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.Status,
		&i.CurrentStage,
		&i.TotalStages,
		&i.Priority,
		&i.DueDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApprovalTaskStatus = `-- name: UpdateApprovalTaskStatus :one
UPDATE approval_tasks
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, document_id, assigned_to, assigned_by, status, current_stage, total_stages, priority, due_date, notes, created_at, updated_at
`

type UpdateApprovalTaskStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateApprovalTaskStatus(ctx context.Context, arg UpdateApprovalTaskStatusParams) (ApprovalTask, error) {
	row := q.db.QueryRow(ctx, updateApprovalTaskStatus, arg.ID, arg.Status)
	var i ApprovalTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AssignedTo,
		&i.AssignedBy,
		&i.Status,
		&i.CurrentStage,
		&i.TotalStages,
		&i.Priority,
		&i.DueDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
