// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveDocument = `-- name: ApproveDocument :one
UPDATE documents
SET status = 'APPROVED',
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at
`

func (q *Queries) ApproveDocument(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, approveDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedBy,
		&i.Department,
		&i.WorkflowID,
		&i.Data,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countDocuments = `-- name: CountDocuments :one
SELECT COUNT(*) FROM documents
`

func (q *Queries) CountDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsByCreator = `-- name: CountDocumentsByCreator :one
SELECT COUNT(*) FROM documents
WHERE created_by = $1
`

func (q *Queries) CountDocumentsByCreator(ctx context.Context, createdBy pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByCreator, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsByStatus = `-- name: CountDocumentsByStatus :one
SELECT COUNT(*) FROM documents
WHERE status = $1
`

func (q *Queries) CountDocumentsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsByType = `-- name: CountDocumentsByType :one
SELECT COUNT(*) FROM documents
WHERE document_type = $1
`

func (q *Queries) CountDocumentsByType(ctx context.Context, documentType string) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByType, documentType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    document_type,
    document_number,
    title,
    description,
    amount,
    currency,
    status,
    created_by,
    department,
    workflow_id,
    data,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at
`

type CreateDocumentParams struct {
	DocumentType   string         `json:"document_type"`
	DocumentNumber string         `json:"document_number"`
	Title          string         `json:"title"`
	Description    pgtype.Text    `json:"description"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       pgtype.Text    `json:"currency"`
	Status         string         `json:"status"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
	Department     pgtype.Text    `json:"department"`
	WorkflowID     pgtype.UUID    `json:"workflow_id"`
	Data           []byte         `json:"data"`
	Metadata       []byte         `json:"metadata"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.Title,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.CreatedBy,
		arg.Department,
		arg.WorkflowID,
		arg.Data,
		arg.Metadata,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedBy,
		&i.Department,
		&i.WorkflowID,
		&i.Data,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocumentAmountSum = `-- name: GetDocumentAmountSum :one
SELECT COALESCE(SUM(amount), 0) FROM documents
WHERE status = $1 AND created_at >= $2
`

type GetDocumentAmountSumParams struct {
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetDocumentAmountSum(ctx context.Context, arg GetDocumentAmountSumParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getDocumentAmountSum, arg.Status, arg.CreatedAt)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at FROM documents
WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedBy,
		&i.Department,
		&i.WorkflowID,
		&i.Data,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDocumentByNumber = `-- name: GetDocumentByNumber :one
SELECT id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at FROM documents
WHERE document_number = $1
`

func (q *Queries) GetDocumentByNumber(ctx context.Context, documentNumber string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByNumber, documentNumber)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedBy,
		&i.Department,
		&i.WorkflowID,
		&i.Data,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at FROM documents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedBy,
			&i.Department,
			&i.WorkflowID,
			&i.Data,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByCreator = `-- name: ListDocumentsByCreator :many
SELECT id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at FROM documents
WHERE created_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByCreatorParams struct {
	CreatedBy pgtype.UUID `json:"created_by"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListDocumentsByCreator(ctx context.Context, arg ListDocumentsByCreatorParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByCreator, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedBy,
			&i.Department,
			&i.WorkflowID,
			&i.Data,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByDepartment = `-- name: ListDocumentsByDepartment :many
SELECT id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at FROM documents
WHERE department = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByDepartmentParams struct {
	Department pgtype.Text `json:"department"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListDocumentsByDepartment(ctx context.Context, arg ListDocumentsByDepartmentParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByDepartment, arg.Department, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedBy,
			&i.Department,
			&i.WorkflowID,
			&i.Data,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByStatus = `-- name: ListDocumentsByStatus :many
SELECT id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at FROM documents
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDocumentsByStatus(ctx context.Context, arg ListDocumentsByStatusParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedBy,
			&i.Department,
			&i.WorkflowID,
			&i.Data,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByType = `-- name: ListDocumentsByType :many
SELECT id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at FROM documents
WHERE document_type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByTypeParams struct {
	DocumentType string `json:"document_type"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListDocumentsByType(ctx context.Context, arg ListDocumentsByTypeParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByType, arg.DocumentType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedBy,
			&i.Department,
			&i.WorkflowID,
			&i.Data,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByTypeAndStatus = `-- name: ListDocumentsByTypeAndStatus :many
SELECT id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at FROM documents
WHERE document_type = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListDocumentsByTypeAndStatusParams struct {
	DocumentType string `json:"document_type"`
	Status       string `json:"status"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListDocumentsByTypeAndStatus(ctx context.Context, arg ListDocumentsByTypeAndStatusParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByTypeAndStatus,
		arg.DocumentType,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedBy,
			&i.Department,
			&i.WorkflowID,
			&i.Data,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByWorkflow = `-- name: ListDocumentsByWorkflow :many
SELECT id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at FROM documents
WHERE workflow_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByWorkflowParams struct {
	WorkflowID pgtype.UUID `json:"workflow_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListDocumentsByWorkflow(ctx context.Context, arg ListDocumentsByWorkflowParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByWorkflow, arg.WorkflowID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedBy,
			&i.Department,
			&i.WorkflowID,
			&i.Data,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectDocument = `-- name: RejectDocument :one
UPDATE documents
SET status = 'REJECTED',
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at
`

func (q *Queries) RejectDocument(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, rejectDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedBy,
		&i.Department,
		&i.WorkflowID,
		&i.Data,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
	)
	return i, err
}

const submitDocument = `-- name: SubmitDocument :one
UPDATE documents
SET status = 'SUBMITTED',
    submitted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at
`

func (q *Queries) SubmitDocument(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, submitDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedBy,
		&i.Department,
		&i.WorkflowID,
		&i.Data,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET title = $2,
    description = $3,
    amount = $4,
    currency = $5,
    data = $6,
    metadata = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at
`

type UpdateDocumentParams struct {
	ID          pgtype.UUID    `json:"id"`
	Title       string         `json:"title"`
	Description pgtype.Text    `json:"description"`
	Amount      pgtype.Numeric `json:"amount"`
	Currency    pgtype.Text    `json:"currency"`
	Data        []byte         `json:"data"`
	Metadata    []byte         `json:"metadata"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.Data,
		arg.Metadata,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedBy,
		&i.Department,
		&i.WorkflowID,
		&i.Data,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
UPDATE documents
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, document_type, document_number, title, description, amount, currency, status, created_by, department, workflow_id, data, metadata, created_at, updated_at, submitted_at, completed_at
`

type UpdateDocumentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentStatus, arg.ID, arg.Status)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedBy,
		&i.Department,
		&i.WorkflowID,
		&i.Data,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CompletedAt,
	)
	return i, err
}
