// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApprovalHistory struct {
	ID        pgtype.UUID      `json:"id"`
	TaskID    pgtype.UUID      `json:"task_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Action    string           `json:"action"`
	Stage     int32            `json:"stage"`
	Comment   pgtype.Text      `json:"comment"`
	Signature pgtype.Text      `json:"signature"`
	IpAddress pgtype.Text      `json:"ip_address"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type ApprovalTask struct {
	ID           pgtype.UUID      `json:"id"`
	DocumentID   pgtype.UUID      `json:"document_id"`
	AssignedTo   pgtype.UUID      `json:"assigned_to"`
	AssignedBy   pgtype.UUID      `json:"assigned_by"`
	Status       string           `json:"status"`
	CurrentStage int32            `json:"current_stage"`
	TotalStages  int32            `json:"total_stages"`
	Priority     pgtype.Text      `json:"priority"`
	DueDate      pgtype.Timestamp `json:"due_date"`
	Notes        pgtype.Text      `json:"notes"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type AuditLog struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	Action       string           `json:"action"`
	ResourceType string           `json:"resource_type"`
	ResourceID   pgtype.UUID      `json:"resource_id"`
	Changes      []byte           `json:"changes"`
	IpAddress    pgtype.Text      `json:"ip_address"`
	UserAgent    pgtype.Text      `json:"user_agent"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Document struct {
	ID             pgtype.UUID      `json:"id"`
	DocumentType   string           `json:"document_type"`
	DocumentNumber string           `json:"document_number"`
	Title          string           `json:"title"`
	Description    pgtype.Text      `json:"description"`
	Amount         pgtype.Numeric   `json:"amount"`
	Currency       pgtype.Text      `json:"currency"`
	Status         string           `json:"status"`
	CreatedBy      pgtype.UUID      `json:"created_by"`
	Department     pgtype.Text      `json:"department"`
	WorkflowID     pgtype.UUID      `json:"workflow_id"`
	Data           []byte           `json:"data"`
	Metadata       []byte           `json:"metadata"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	SubmittedAt    pgtype.Timestamp `json:"submitted_at"`
	CompletedAt    pgtype.Timestamp `json:"completed_at"`
}

type Notification struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	Type         string           `json:"type"`
	Title        string           `json:"title"`
	Message      string           `json:"message"`
	RelatedID    pgtype.UUID      `json:"related_id"`
	IsRead       pgtype.Bool      `json:"is_read"`
	SentViaEmail pgtype.Bool      `json:"sent_via_email"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type PasswordReset struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Used      pgtype.Bool      `json:"used"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	RefreshToken string           `json:"refresh_token"`
	IpAddress    pgtype.Text      `json:"ip_address"`
	UserAgent    pgtype.Text      `json:"user_agent"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID                  pgtype.UUID      `json:"id"`
	Email               string           `json:"email"`
	PasswordHash        string           `json:"password_hash"`
	Name                string           `json:"name"`
	Role                string           `json:"role"`
	Department          pgtype.Text      `json:"department"`
	IsActive            pgtype.Bool      `json:"is_active"`
	EmailVerified       pgtype.Bool      `json:"email_verified"`
	FailedLoginAttempts pgtype.Int4      `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamp `json:"locked_until"`
	LastLogin           pgtype.Timestamp `json:"last_login"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

type Workflow struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	DocumentType string           `json:"document_type"`
	Stages       []byte           `json:"stages"`
	IsActive     pgtype.Bool      `json:"is_active"`
	CreatedBy    pgtype.UUID      `json:"created_by"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
