// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsByType = `-- name: CountNotificationsByType :one
SELECT COUNT(*) FROM notifications
WHERE type = $1
`

func (q *Queries) CountNotificationsByType(ctx context.Context, type_ string) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByType, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotificationsByUser = `-- name: CountNotificationsByUser :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1
`

func (q *Queries) CountNotificationsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotificationsByUser = `-- name: CountUnreadNotificationsByUser :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotificationsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotificationsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id,
    type,
    title,
    message,
    related_id,
    sent_via_email
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, type, title, message, related_id, is_read, sent_via_email, created_at
`

type CreateNotificationParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Type         string      `json:"type"`
	Title        string      `json:"title"`
	Message      string      `json:"message"`
	RelatedID    pgtype.UUID `json:"related_id"`
	SentViaEmail pgtype.Bool `json:"sent_via_email"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.RelatedID,
		arg.SentViaEmail,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.RelatedID,
		&i.IsRead,
		&i.SentViaEmail,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotification, id)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < $1
`

func (q *Queries) DeleteOldNotifications(ctx context.Context, createdAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications, createdAt)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, type, title, message, related_id, is_read, sent_via_email, created_at FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.RelatedID,
		&i.IsRead,
		&i.SentViaEmail,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByRelatedID = `-- name: ListNotificationsByRelatedID :many
SELECT id, user_id, type, title, message, related_id, is_read, sent_via_email, created_at FROM notifications
WHERE related_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListNotificationsByRelatedID(ctx context.Context, relatedID pgtype.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByRelatedID, relatedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.RelatedID,
			&i.IsRead,
			&i.SentViaEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByType = `-- name: ListNotificationsByType :many
SELECT id, user_id, type, title, message, related_id, is_read, sent_via_email, created_at FROM notifications
WHERE type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByTypeParams struct {
	Type   string `json:"type"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListNotificationsByType(ctx context.Context, arg ListNotificationsByTypeParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.RelatedID,
			&i.IsRead,
			&i.SentViaEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, type, title, message, related_id, is_read, sent_via_email, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.RelatedID,
			&i.IsRead,
			&i.SentViaEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotificationsByUser = `-- name: ListUnreadNotificationsByUser :many
SELECT id, user_id, type, title, message, related_id, is_read, sent_via_email, created_at FROM notifications
WHERE user_id = $1 AND is_read = false
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUnreadNotificationsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUnreadNotificationsByUser(ctx context.Context, arg ListUnreadNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.RelatedID,
			&i.IsRead,
			&i.SentViaEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = true
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET is_read = true
WHERE id = $1
RETURNING id, user_id, type, title, message, related_id, is_read, sent_via_email, created_at
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationAsRead, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.RelatedID,
		&i.IsRead,
		&i.SentViaEmail,
		&i.CreatedAt,
	)
	return i, err
}
