// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateUser(ctx context.Context, id pgtype.UUID) error
	ActivateWorkflow(ctx context.Context, id pgtype.UUID) (Workflow, error)
	ApproveDocument(ctx context.Context, id pgtype.UUID) (Document, error)
	CountActiveSessions(ctx context.Context) (int64, error)
	CountActiveUsers(ctx context.Context) (int64, error)
	CountActiveWorkflows(ctx context.Context) (int64, error)
	CountApprovalHistoryByTask(ctx context.Context, taskID pgtype.UUID) (int64, error)
	CountApprovalHistoryByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountApprovalTasksByAssignee(ctx context.Context, assignedTo pgtype.UUID) (int64, error)
	CountApprovalTasksByStatus(ctx context.Context, status string) (int64, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountAuditLogsByResource(ctx context.Context, arg CountAuditLogsByResourceParams) (int64, error)
	CountAuditLogsByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountDocuments(ctx context.Context) (int64, error)
	CountDocumentsByCreator(ctx context.Context, createdBy pgtype.UUID) (int64, error)
	CountDocumentsByStatus(ctx context.Context, status string) (int64, error)
	CountDocumentsByType(ctx context.Context, documentType string) (int64, error)
	CountNotificationsByType(ctx context.Context, type_ string) (int64, error)
	CountNotificationsByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountPendingApprovalTasksByAssignee(ctx context.Context, assignedTo pgtype.UUID) (int64, error)
	CountUnreadNotificationsByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountUserActiveSessions(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWorkflows(ctx context.Context) (int64, error)
	CountWorkflowsByDocumentType(ctx context.Context, documentType string) (int64, error)
	CreateApprovalHistoryEntry(ctx context.Context, arg CreateApprovalHistoryEntryParams) (ApprovalHistory, error)
	CreateApprovalTask(ctx context.Context, arg CreateApprovalTaskParams) (ApprovalTask, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	DeactivateUser(ctx context.Context, id pgtype.UUID) error
	DeactivateWorkflow(ctx context.Context, id pgtype.UUID) (Workflow, error)
	DeleteApprovalHistory(ctx context.Context, id pgtype.UUID) error
	DeleteApprovalTask(ctx context.Context, id pgtype.UUID) error
	DeleteDocument(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredPasswordResets(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteNotification(ctx context.Context, id pgtype.UUID) error
	DeleteOldAuditLogs(ctx context.Context, createdAt pgtype.Timestamp) error
	DeleteOldNotifications(ctx context.Context, createdAt pgtype.Timestamp) error
	DeletePasswordResetsByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteSessionByRefreshToken(ctx context.Context, refreshToken string) error
	DeleteSessionsByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteUsedPasswordResets(ctx context.Context) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DeleteWorkflow(ctx context.Context, id pgtype.UUID) error
	GetApprovalHistoryByID(ctx context.Context, id pgtype.UUID) (ApprovalHistory, error)
	GetApprovalTaskByID(ctx context.Context, id pgtype.UUID) (ApprovalTask, error)
	GetAuditLogByID(ctx context.Context, id pgtype.UUID) (AuditLog, error)
	GetDefaultWorkflowByDocumentType(ctx context.Context, documentType string) (Workflow, error)
	GetDocumentAmountSum(ctx context.Context, arg GetDocumentAmountSumParams) (interface{}, error)
	GetDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error)
	GetDocumentByNumber(ctx context.Context, documentNumber string) (Document, error)
	GetLatestApprovalHistoryByTask(ctx context.Context, taskID pgtype.UUID) (ApprovalHistory, error)
	GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error)
	GetPasswordResetByToken(ctx context.Context, token string) (PasswordReset, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error)
	GetSessionsByUserID(ctx context.Context, userID pgtype.UUID) ([]Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetWorkflowByID(ctx context.Context, id pgtype.UUID) (Workflow, error)
	IncrementFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error
	ListActiveWorkflows(ctx context.Context, arg ListActiveWorkflowsParams) ([]Workflow, error)
	ListActiveWorkflowsByDocumentType(ctx context.Context, arg ListActiveWorkflowsByDocumentTypeParams) ([]Workflow, error)
	ListApprovalHistoryByAction(ctx context.Context, arg ListApprovalHistoryByActionParams) ([]ApprovalHistory, error)
	ListApprovalHistoryByTask(ctx context.Context, taskID pgtype.UUID) ([]ApprovalHistory, error)
	ListApprovalHistoryByUser(ctx context.Context, arg ListApprovalHistoryByUserParams) ([]ApprovalHistory, error)
	ListApprovalTasksByAssignee(ctx context.Context, arg ListApprovalTasksByAssigneeParams) ([]ApprovalTask, error)
	ListApprovalTasksByAssigneeAndStatus(ctx context.Context, arg ListApprovalTasksByAssigneeAndStatusParams) ([]ApprovalTask, error)
	ListApprovalTasksByDocument(ctx context.Context, documentID pgtype.UUID) ([]ApprovalTask, error)
	ListApprovalTasksByStatus(ctx context.Context, arg ListApprovalTasksByStatusParams) ([]ApprovalTask, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByDateRange(ctx context.Context, arg ListAuditLogsByDateRangeParams) ([]AuditLog, error)
	ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]AuditLog, error)
	ListAuditLogsByResourceType(ctx context.Context, arg ListAuditLogsByResourceTypeParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error)
	ListDocumentsByCreator(ctx context.Context, arg ListDocumentsByCreatorParams) ([]Document, error)
	ListDocumentsByDepartment(ctx context.Context, arg ListDocumentsByDepartmentParams) ([]Document, error)
	ListDocumentsByStatus(ctx context.Context, arg ListDocumentsByStatusParams) ([]Document, error)
	ListDocumentsByType(ctx context.Context, arg ListDocumentsByTypeParams) ([]Document, error)
	ListDocumentsByTypeAndStatus(ctx context.Context, arg ListDocumentsByTypeAndStatusParams) ([]Document, error)
	ListDocumentsByWorkflow(ctx context.Context, arg ListDocumentsByWorkflowParams) ([]Document, error)
	ListNotificationsByRelatedID(ctx context.Context, relatedID pgtype.UUID) ([]Notification, error)
	ListNotificationsByType(ctx context.Context, arg ListNotificationsByTypeParams) ([]Notification, error)
	ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error)
	ListOverdueApprovalTasks(ctx context.Context, arg ListOverdueApprovalTasksParams) ([]ApprovalTask, error)
	ListPendingApprovalTasks(ctx context.Context, arg ListPendingApprovalTasksParams) ([]ApprovalTask, error)
	ListUnreadNotificationsByUser(ctx context.Context, arg ListUnreadNotificationsByUserParams) ([]Notification, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByDepartment(ctx context.Context, department pgtype.Text) ([]User, error)
	ListUsersByRole(ctx context.Context, role string) ([]User, error)
	ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error)
	ListWorkflowsByDocumentType(ctx context.Context, arg ListWorkflowsByDocumentTypeParams) ([]Workflow, error)
	LockUserAccount(ctx context.Context, arg LockUserAccountParams) error
	MarkAllNotificationsAsRead(ctx context.Context, userID pgtype.UUID) error
	MarkNotificationAsRead(ctx context.Context, id pgtype.UUID) (Notification, error)
	MarkPasswordResetAsUsed(ctx context.Context, id pgtype.UUID) error
	ReassignApprovalTask(ctx context.Context, arg ReassignApprovalTaskParams) (ApprovalTask, error)
	RejectDocument(ctx context.Context, id pgtype.UUID) (Document, error)
	ResetFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error
	SubmitDocument(ctx context.Context, id pgtype.UUID) (Document, error)
	UpdateApprovalTaskNotes(ctx context.Context, arg UpdateApprovalTaskNotesParams) (ApprovalTask, error)
	UpdateApprovalTaskStage(ctx context.Context, arg UpdateApprovalTaskStageParams) (ApprovalTask, error)
	UpdateApprovalTaskStatus(ctx context.Context, arg UpdateApprovalTaskStatusParams) (ApprovalTask, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error)
	UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error)
}

var _ Querier = (*Queries)(nil)
