// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateWorkflow = `-- name: ActivateWorkflow :one
UPDATE workflows
SET is_active = true,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, document_type, stages, is_active, created_by, created_at, updated_at
`

func (q *Queries) ActivateWorkflow(ctx context.Context, id pgtype.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, activateWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.Stages,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveWorkflows = `-- name: CountActiveWorkflows :one
SELECT COUNT(*) FROM workflows
WHERE is_active = true
`

func (q *Queries) CountActiveWorkflows(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWorkflows)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkflows = `-- name: CountWorkflows :one
SELECT COUNT(*) FROM workflows
`

func (q *Queries) CountWorkflows(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflows)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkflowsByDocumentType = `-- name: CountWorkflowsByDocumentType :one
SELECT COUNT(*) FROM workflows
WHERE document_type = $1
`

func (q *Queries) CountWorkflowsByDocumentType(ctx context.Context, documentType string) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowsByDocumentType, documentType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (
    name,
    description,
    document_type,
    stages,
    is_active,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, description, document_type, stages, is_active, created_by, created_at, updated_at
`

type CreateWorkflowParams struct {
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	DocumentType string      `json:"document_type"`
	Stages       []byte      `json:"stages"`
	IsActive     pgtype.Bool `json:"is_active"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.Name,
		arg.Description,
		arg.DocumentType,
		arg.Stages,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.Stages,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateWorkflow = `-- name: DeactivateWorkflow :one
UPDATE workflows
SET is_active = false,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, document_type, stages, is_active, created_by, created_at, updated_at
`

func (q *Queries) DeactivateWorkflow(ctx context.Context, id pgtype.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, deactivateWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.Stages,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows
WHERE id = $1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, id)
	return err
}

const getDefaultWorkflowByDocumentType = `-- name: GetDefaultWorkflowByDocumentType :one
SELECT id, name, description, document_type, stages, is_active, created_by, created_at, updated_at FROM workflows
WHERE document_type = $1 AND is_active = true
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetDefaultWorkflowByDocumentType(ctx context.Context, documentType string) (Workflow, error) {
	row := q.db.QueryRow(ctx, getDefaultWorkflowByDocumentType, documentType)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.Stages,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, name, description, document_type, stages, is_active, created_by, created_at, updated_at FROM workflows
WHERE id = $1
`

func (q *Queries) GetWorkflowByID(ctx context.Context, id pgtype.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByID, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.Stages,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWorkflows = `-- name: ListActiveWorkflows :many
SELECT id, name, description, document_type, stages, is_active, created_by, created_at, updated_at FROM workflows
WHERE is_active = true
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveWorkflowsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveWorkflows(ctx context.Context, arg ListActiveWorkflowsParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listActiveWorkflows, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.Stages,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWorkflowsByDocumentType = `-- name: ListActiveWorkflowsByDocumentType :many
SELECT id, name, description, document_type, stages, is_active, created_by, created_at, updated_at FROM workflows
WHERE document_type = $1 AND is_active = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveWorkflowsByDocumentTypeParams struct {
	DocumentType string `json:"document_type"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListActiveWorkflowsByDocumentType(ctx context.Context, arg ListActiveWorkflowsByDocumentTypeParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listActiveWorkflowsByDocumentType, arg.DocumentType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.Stages,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, name, description, document_type, stages, is_active, created_by, created_at, updated_at FROM workflows
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListWorkflowsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.Stages,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsByDocumentType = `-- name: ListWorkflowsByDocumentType :many
SELECT id, name, description, document_type, stages, is_active, created_by, created_at, updated_at FROM workflows
WHERE document_type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkflowsByDocumentTypeParams struct {
	DocumentType string `json:"document_type"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListWorkflowsByDocumentType(ctx context.Context, arg ListWorkflowsByDocumentTypeParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflowsByDocumentType, arg.DocumentType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.Stages,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows
SET name = $2,
    description = $3,
    stages = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, document_type, stages, is_active, created_by, created_at, updated_at
`

type UpdateWorkflowParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Stages      []byte      `json:"stages"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Stages,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.Stages,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
